import { ScrollView, StyleSheet, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";

function Dot({ color, size = 8 }: { color: string; size?: number }) {
  return <View style={{ width: size, height: size, borderRadius: size / 2, backgroundColor: color }} />;
}

function SwissSignal() {
  return (
    <View style={[styles.artboard, styles.swissBoard]}>
      <View style={styles.swissTopLine} />
      <View style={styles.swissHeader}><Text style={styles.swissBrand}>IRON / RISE</Text><Text style={styles.swissDate}>19 · 08</Text></View>
      <View style={styles.swissHero}><Text style={styles.swissNumber}>01</Text><View style={styles.swissHeroCopy}><Text style={styles.swissKicker}>СЕГОДНЯ</Text><Text style={styles.swissTitle}>ВЕРХ{`\n`}СИЛА</Text><View style={styles.swissStripe} /></View></View>
      <View style={styles.swissGrid}><View><Text style={styles.swissKicker}>ПЛАН</Text><Text style={styles.swissList}>Жим штанги{`\n`}Тяга блока{`\n`}Жим сидя{`\n`}Сгибания</Text></View><View style={styles.swissDayCol}>{["П", "В", "С", "Ч", "П", "С", "В"].map((day, index) => <View key={day} style={styles.swissDay}><Text style={styles.swissDayText}>{day}</Text><View style={[styles.swissBar, { height: 14 + index * 5, backgroundColor: index === 3 ? "#E6372A" : "#234ED8" }]} /></View>)}</View></View>
      <View style={styles.swissFooter}><Text style={styles.swissFooterText}>3 ТРЕНИРОВКИ</Text><Text style={styles.swissFooterText}>17.9 Т ОБЪЁМ</Text></View>
    </View>
  );
}

function BrutalGrid() {
  const items = [["ЖИМ", "03×08", "85"], ["ТЯГА", "03×10", "65"], ["ПЛЕЧИ", "04×12", "24"], ["БИЦЕПС", "03×10", "30"]];
  return (
    <View style={[styles.artboard, styles.brutalBoard]}>
      <View style={styles.brutalHeader}><View><Text style={styles.brutalLive}>● LIVE</Text><Text style={styles.brutalTimer}>42:00</Text></View><View style={styles.brutalBadge}><Text style={styles.brutalBadgeText}>UPPER{`\n`}01</Text></View></View>
      <Text style={styles.brutalCaption}>РАБОЧИЙ СПИСОК / ВТОРНИК</Text>
      <View style={styles.brutalList}>{items.map(([name, sets, kg], index) => <View key={name} style={styles.brutalRow}><Text style={styles.brutalIndex}>0{index + 1}</Text><View style={{ flex: 1 }}><Text style={styles.brutalName}>{name}</Text><View style={styles.brutalMeter}><View style={[styles.brutalFill, { width: `${42 + index * 13}%` }]} /></View></View><Text style={styles.brutalSets}>{sets}</Text><Text style={styles.brutalKg}>{kg}</Text></View>)}</View>
      <View style={styles.brutalHeatmap}>{Array.from({ length: 24 }, (_, index) => <View key={index} style={[styles.brutalCell, { backgroundColor: index % 7 === 1 || index % 8 === 0 ? "#E9FF35" : index % 5 === 0 ? "#FF3B30" : "#20242B" }]} />)}</View>
      <View style={styles.brutalStart}><Text style={styles.brutalStartText}>НАЧАТЬ / 04 УПРАЖНЕНИЯ</Text><Text style={styles.brutalArrow}>→</Text></View>
    </View>
  );
}

function LiquidGlass() {
  return (
    <View style={[styles.artboard, styles.liquidBoard]}>
      <View style={styles.liquidBlobOne} /><View style={styles.liquidBlobTwo} /><View style={styles.liquidBlobThree} />
      <View style={styles.liquidNav}><Text style={styles.liquidBrand}>ironrise</Text><Text style={styles.liquidNavText}>19 AUG</Text></View>
      <View style={styles.orb}><View style={styles.orbInner}><Text style={styles.orbPercent}>68%</Text><Text style={styles.orbLabel}>ТРЕНИРОВКА</Text><Text style={styles.orbTime}>42 мин</Text></View></View>
      <View style={styles.liquidArc}><View style={styles.liquidChip}><Text style={styles.liquidChipValue}>3.4 т</Text><Text style={styles.liquidChipLabel}>ОБЪЁМ</Text></View><View style={styles.liquidChip}><Text style={styles.liquidChipValue}>12</Text><Text style={styles.liquidChipLabel}>СЕТОВ</Text></View><View style={styles.liquidChip}><Text style={styles.liquidChipValue}>01:30</Text><Text style={styles.liquidChipLabel}>ОТДЫХ</Text></View></View>
      <View style={styles.liquidCarousel}><Text style={styles.liquidOverline}>СЛЕДУЮЩЕЕ</Text><Text style={styles.liquidExercise}>Жим штанги лёжа</Text><View style={styles.liquidProgress}><View style={styles.liquidProgressFill} /></View><Text style={styles.liquidMeta}>3 подхода · 85 кг · 8 повторений</Text></View>
      <View style={styles.liquidDock}><Dot color="#4DEEEA" size={9} /><Dot color="#ffffff88" size={9} /><Dot color="#ffffff88" size={9} /><Dot color="#ffffff88" size={9} /><Dot color="#ffffff88" size={9} /></View>
    </View>
  );
}

function PocketCoach() {
  const days = ["П", "В", "С", "Ч", "П", "С", "В"];
  return (
    <View style={[styles.artboard, styles.coachBoard]}>
      <View style={styles.coachHeader}><View><Text style={styles.coachTiny}>ТВОЙ ТРЕНЕР</Text><Text style={styles.coachTitle}>Привет, Макс!</Text></View><View style={styles.coachAvatar}><Text style={styles.coachAvatarText}>↑</Text></View></View>
      <View style={styles.coachDays}>{days.map((day, index) => <View key={`${day}-${index}`} style={[styles.coachDay, { backgroundColor: ["#FF83B5", "#82C7FF", "#7EE0B5", "#FF9D3D", "#8B6FE8", "#F7EFA7", "#D9E4F8"][index] }]}><Text style={styles.coachDayText}>{day}</Text>{index === 3 && <View style={styles.coachDayTick}><Text style={styles.coachDayTickText}>✓</Text></View>}</View>)}</View>
      <View style={styles.coachNote}><View style={styles.coachTape} /><Text style={styles.coachNoteTitle}>СИЛОВОЙ ДЕНЬ</Text><Text style={styles.coachNoteCopy}>Сегодня сделаем 4 упражнения для верха тела.</Text><View style={styles.coachPlay}><Text style={styles.coachPlayText}>▶ НАЧАТЬ 42 МИН</Text></View></View>
      <View style={styles.coachPath}><View style={[styles.coachStation, { backgroundColor: "#FF9D3D" }]}><Text>1</Text></View><View style={styles.coachLine} /><View style={[styles.coachStation, { backgroundColor: "#82C7FF" }]}><Text>2</Text></View><View style={styles.coachLine} /><View style={[styles.coachStation, { backgroundColor: "#7EE0B5" }]}><Text>3</Text></View><View style={styles.coachLine} /><View style={[styles.coachStation, { backgroundColor: "#8B6FE8" }]}><Text>4</Text></View></View>
      <View style={styles.coachCards}><View style={[styles.coachSmallCard, { backgroundColor: "#FFDEF0", transform: [{ rotate: "-2deg" }] }]}><Text style={styles.coachSmallTop}>СЕРИЯ</Text><Text style={styles.coachSmallValue}>🔥 4 дня</Text></View><View style={[styles.coachSmallCard, { backgroundColor: "#D9F9EA", transform: [{ rotate: "2deg" }] }]}><Text style={styles.coachSmallTop}>РЕКОРД</Text><Text style={styles.coachSmallValue}>+5 кг</Text></View></View>
    </View>
  );
}

function TrainingLedger() {
  const rows = [["Жим лёжа", "3×8", "85"], ["Тяга блока", "3×10", "65"], ["Жим сидя", "4×12", "24"], ["Бицепс", "3×10", "30"]];
  return (
    <View style={[styles.artboard, styles.ledgerBoard]}>
      <View style={styles.ledgerHeader}><View><Text style={styles.ledgerBrand}>IRONRISE / LOG 08</Text><Text style={styles.ledgerDate}>Вторник, 19 августа</Text></View><View style={styles.ledgerStamp}><Text style={styles.ledgerStampText}>UPPER{`\n`}DAY</Text></View></View>
      <View style={styles.ledgerCalendar}>{[12, 13, 14, 15, 16, 17, 18].map((day, index) => <View key={day} style={styles.ledgerCalendarDay}><Text style={styles.ledgerCalendarText}>{day}</Text><View style={[styles.ledgerCalendarMark, { backgroundColor: index === 5 ? "#E24A3B" : index === 1 || index === 3 ? "#2155CD" : "#DDD4C6" }]} /></View>)}</View>
      <View style={styles.ledgerTableHead}><Text style={[styles.ledgerHeadText, { flex: 1.6 }]}>УПРАЖНЕНИЕ</Text><Text style={styles.ledgerHeadText}>СЕТЫ</Text><Text style={styles.ledgerHeadText}>ВЕС</Text></View>
      <View style={styles.ledgerTable}>{rows.map(([name, sets, kg], index) => <View key={name} style={styles.ledgerRow}><View style={[styles.ledgerMarker, { backgroundColor: index % 2 ? "#E24A3B" : "#2155CD" }]} /><Text style={[styles.ledgerName, { flex: 1.6 }]}>{name}</Text><Text style={styles.ledgerCell}>{sets}</Text><Text style={styles.ledgerCell}>{kg}</Text></View>)}</View>
      <View style={styles.ledgerChart}><View style={styles.ledgerChartLabels}><Text style={styles.ledgerChartTitle}>1RM / ЖИМ</Text><Text style={styles.ledgerChartValue}>104 кг</Text></View><View style={styles.ledgerChartLine}><View style={[styles.ledgerPoint, { left: "7%", bottom: "24%" }]} /><View style={[styles.ledgerPoint, { left: "31%", bottom: "38%" }]} /><View style={[styles.ledgerPoint, { left: "55%", bottom: "49%" }]} /><View style={[styles.ledgerPoint, { left: "79%", bottom: "72%", backgroundColor: "#D8A11D" }]} /><View style={styles.ledgerTrend} /></View></View>
    </View>
  );
}

export default function DesignGalleryScreen() {
  return (
    <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-background">
      <ScrollView contentContainerStyle={styles.page} showsVerticalScrollIndicator={false}>
        <Text style={styles.pageEyebrow}>IRONRISE / DESIGN LAB</Text>
        <Text style={styles.pageTitle}>Пять разных композиций</Text>
        <Text style={styles.pageIntro}>Здесь различаются не только цвета: у каждого направления своя структура, плотность и способ показа тренировки.</Text>
        <Text style={styles.variantLabel}>01 — SWISS SIGNAL / редакционная сетка</Text><SwissSignal />
        <Text style={styles.variantLabel}>02 — BRUTAL GRID / рабочая панель</Text><BrutalGrid />
        <Text style={styles.variantLabel}>03 — LIQUID GLASS / прогресс-орб</Text><LiquidGlass />
        <Text style={styles.variantLabel}>04 — POCKET COACH / игровой план</Text><PocketCoach />
        <Text style={styles.variantLabel}>05 — TRAINING LEDGER / журнал</Text><TrainingLedger />
      </ScrollView>
    </ScreenContainer>
  );
}

const styles = StyleSheet.create({
  page: { padding: 20, paddingBottom: 44, gap: 13, backgroundColor: "#ECE8F2" },
  pageEyebrow: { color: "#6C4AD8", fontSize: 10, fontWeight: "900", letterSpacing: 1.1 }, pageTitle: { color: "#201831", fontSize: 25, fontWeight: "900" }, pageIntro: { color: "#665D73", fontSize: 13, lineHeight: 19, marginBottom: 5 }, variantLabel: { color: "#423755", fontSize: 10, fontWeight: "900", letterSpacing: 0.6, marginTop: 7 },
  artboard: { width: "100%", height: 570, borderRadius: 26, overflow: "hidden", shadowColor: "#201831", shadowOpacity: 0.16, shadowRadius: 13, elevation: 5 },
  swissBoard: { backgroundColor: "#F8F1E5", padding: 20 }, swissTopLine: { height: 7, backgroundColor: "#E6372A", position: "absolute", top: 0, left: 0, right: 0 }, swissHeader: { flexDirection: "row", justifyContent: "space-between", marginTop: 12 }, swissBrand: { color: "#161616", fontWeight: "900", letterSpacing: 1.2, fontSize: 11 }, swissDate: { color: "#234ED8", fontWeight: "900", fontSize: 12 }, swissHero: { flexDirection: "row", borderBottomWidth: 1, borderColor: "#161616", paddingBottom: 18, marginTop: 12 }, swissNumber: { color: "#E6372A", fontWeight: "900", fontSize: 104, letterSpacing: -9, lineHeight: 100 }, swissHeroCopy: { flex: 1, alignSelf: "flex-end", paddingBottom: 2 }, swissKicker: { color: "#161616", fontSize: 9, fontWeight: "900", letterSpacing: 1 }, swissTitle: { color: "#161616", fontSize: 31, fontWeight: "900", lineHeight: 29, marginTop: 6 }, swissStripe: { height: 10, backgroundColor: "#234ED8", width: "100%", marginTop: 12 }, swissGrid: { flexDirection: "row", justifyContent: "space-between", paddingTop: 20 }, swissList: { color: "#161616", fontSize: 17, lineHeight: 29, fontWeight: "700", marginTop: 10 }, swissDayCol: { flexDirection: "row", alignItems: "flex-end", gap: 6, height: 137 }, swissDay: { width: 16, alignItems: "center", gap: 5, justifyContent: "flex-end" }, swissDayText: { color: "#161616", fontSize: 8, fontWeight: "800" }, swissBar: { width: 13 }, swissFooter: { position: "absolute", left: 20, right: 20, bottom: 20, flexDirection: "row", justifyContent: "space-between", borderTopWidth: 1, borderColor: "#161616", paddingTop: 10 }, swissFooterText: { color: "#161616", fontSize: 9, fontWeight: "900" },
  brutalBoard: { backgroundColor: "#101010", padding: 18 }, brutalHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" }, brutalLive: { color: "#FF3B30", fontSize: 11, fontWeight: "900", letterSpacing: 1 }, brutalTimer: { color: "#F8FAFC", fontSize: 58, fontWeight: "900", letterSpacing: -3 }, brutalBadge: { borderWidth: 2, borderColor: "#E9FF35", padding: 9 }, brutalBadgeText: { color: "#E9FF35", fontWeight: "900", fontSize: 12, lineHeight: 13 }, brutalCaption: { color: "#A5AFBF", fontSize: 9, fontWeight: "900", letterSpacing: 1, marginTop: 9, marginBottom: 8 }, brutalList: { borderTopWidth: 1, borderLeftWidth: 1, borderColor: "#424956" }, brutalRow: { height: 70, borderBottomWidth: 1, borderRightWidth: 1, borderColor: "#424956", flexDirection: "row", alignItems: "center", gap: 9, paddingHorizontal: 9 }, brutalIndex: { color: "#FF6B00", fontSize: 13, fontWeight: "900" }, brutalName: { color: "#F8FAFC", fontSize: 16, fontWeight: "900" }, brutalMeter: { height: 5, backgroundColor: "#20242B", marginTop: 7 }, brutalFill: { height: 5, backgroundColor: "#2563EB" }, brutalSets: { color: "#E9FF35", fontSize: 11, fontWeight: "900" }, brutalKg: { color: "#F8FAFC", fontSize: 17, fontWeight: "900", width: 29, textAlign: "right" }, brutalHeatmap: { flexDirection: "row", flexWrap: "wrap", gap: 5, marginTop: 18 }, brutalCell: { width: "10%", height: 18 }, brutalStart: { backgroundColor: "#E9FF35", position: "absolute", bottom: 18, left: 18, right: 18, height: 57, flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingHorizontal: 14 }, brutalStartText: { color: "#101010", fontWeight: "900", fontSize: 12 }, brutalArrow: { color: "#101010", fontWeight: "900", fontSize: 24 },
  liquidBoard: { backgroundColor: "#181B3A", alignItems: "center", paddingTop: 18 }, liquidBlobOne: { position: "absolute", width: 290, height: 230, borderRadius: 160, backgroundColor: "#4F46E5", opacity: 0.55, top: -70, left: -100 }, liquidBlobTwo: { position: "absolute", width: 250, height: 240, borderRadius: 160, backgroundColor: "#FF7A90", opacity: 0.38, top: 180, right: -130 }, liquidBlobThree: { position: "absolute", width: 260, height: 180, borderRadius: 140, backgroundColor: "#4DEEEA", opacity: 0.25, bottom: -35, left: -90 }, liquidNav: { width: "90%", flexDirection: "row", justifyContent: "space-between" }, liquidBrand: { color: "#FFFFFF", fontWeight: "900", fontSize: 15 }, liquidNavText: { color: "#ffffffa6", fontWeight: "800", fontSize: 10, letterSpacing: 0.8 }, orb: { width: 220, height: 220, borderRadius: 110, marginTop: 20, borderWidth: 14, borderColor: "#4DEEEA", backgroundColor: "#ffffff1A", justifyContent: "center", alignItems: "center", shadowColor: "#4DEEEA", shadowOpacity: 0.6, shadowRadius: 28 }, orbInner: { width: 168, height: 168, borderRadius: 84, justifyContent: "center", alignItems: "center", backgroundColor: "#171B46A8", borderWidth: 1, borderColor: "#ffffff55" }, orbPercent: { color: "#FFFFFF", fontSize: 50, fontWeight: "900", letterSpacing: -3 }, orbLabel: { color: "#B779FF", fontSize: 9, fontWeight: "900", letterSpacing: 1.1 }, orbTime: { color: "#ffffffb0", fontSize: 13, marginTop: 4 }, liquidArc: { flexDirection: "row", gap: 8, marginTop: -6, zIndex: 2 }, liquidChip: { width: 89, height: 65, borderRadius: 18, padding: 10, backgroundColor: "#ffffff24", borderWidth: 1, borderColor: "#ffffff42" }, liquidChipValue: { color: "#FFFFFF", fontWeight: "900", fontSize: 16 }, liquidChipLabel: { color: "#ffffffa8", fontWeight: "800", fontSize: 8, marginTop: 4 }, liquidCarousel: { width: "88%", marginTop: 26, padding: 16, borderRadius: 25, backgroundColor: "#ffffff1F", borderWidth: 1, borderColor: "#ffffff36" }, liquidOverline: { color: "#4DEEEA", fontSize: 9, fontWeight: "900", letterSpacing: 1 }, liquidExercise: { color: "#FFFFFF", fontWeight: "900", fontSize: 19, marginTop: 5 }, liquidProgress: { height: 6, backgroundColor: "#ffffff35", borderRadius: 5, marginTop: 15 }, liquidProgressFill: { height: 6, borderRadius: 5, backgroundColor: "#B779FF", width: "62%" }, liquidMeta: { color: "#ffffffa8", fontSize: 10, marginTop: 8 }, liquidDock: { position: "absolute", bottom: 18, flexDirection: "row", gap: 24, backgroundColor: "#ffffff1F", borderWidth: 1, borderColor: "#ffffff44", paddingHorizontal: 20, paddingVertical: 13, borderRadius: 24 },
  coachBoard: { backgroundColor: "#FFF8E7", padding: 18 }, coachHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, coachTiny: { color: "#8B6FE8", fontSize: 9, fontWeight: "900", letterSpacing: 1 }, coachTitle: { color: "#26314D", fontSize: 25, fontWeight: "900", marginTop: 4 }, coachAvatar: { width: 43, height: 43, borderRadius: 22, backgroundColor: "#FF83B5", alignItems: "center", justifyContent: "center" }, coachAvatarText: { color: "#26314D", fontSize: 24, fontWeight: "900" }, coachDays: { flexDirection: "row", justifyContent: "space-between", marginTop: 17 }, coachDay: { width: 34, height: 34, borderRadius: 17, alignItems: "center", justifyContent: "center" }, coachDayText: { color: "#26314D", fontWeight: "900", fontSize: 11 }, coachDayTick: { position: "absolute", bottom: -6, width: 16, height: 16, borderRadius: 8, backgroundColor: "#26314D", alignItems: "center", justifyContent: "center" }, coachDayTickText: { color: "#FFFFFF", fontSize: 10, fontWeight: "900" }, coachNote: { backgroundColor: "#FFFFFF", marginTop: 26, borderRadius: 8, padding: 19, borderWidth: 2, borderColor: "#26314D", shadowColor: "#26314D", shadowOffset: { width: 5, height: 6 }, shadowOpacity: 0.18, shadowRadius: 0 }, coachTape: { width: 75, height: 15, backgroundColor: "#82C7FF", opacity: 0.8, position: "absolute", top: -8, left: "37%", transform: [{ rotate: "-3deg" }] }, coachNoteTitle: { color: "#26314D", fontSize: 20, fontWeight: "900" }, coachNoteCopy: { color: "#5D6680", fontSize: 12, lineHeight: 18, marginTop: 6 }, coachPlay: { backgroundColor: "#FF9D3D", borderRadius: 20, paddingVertical: 11, alignItems: "center", marginTop: 16, borderWidth: 2, borderColor: "#26314D" }, coachPlayText: { color: "#26314D", fontWeight: "900", fontSize: 11 }, coachPath: { flexDirection: "row", alignItems: "center", justifyContent: "center", marginTop: 29 }, coachStation: { width: 32, height: 32, borderRadius: 16, alignItems: "center", justifyContent: "center", borderWidth: 2, borderColor: "#26314D" }, coachLine: { height: 4, width: 31, backgroundColor: "#26314D" }, coachCards: { flexDirection: "row", gap: 14, marginTop: 25 }, coachSmallCard: { flex: 1, borderRadius: 14, padding: 13, borderWidth: 2, borderColor: "#26314D" }, coachSmallTop: { color: "#26314D", fontSize: 9, fontWeight: "900" }, coachSmallValue: { color: "#26314D", fontSize: 17, fontWeight: "900", marginTop: 8 },
  ledgerBoard: { backgroundColor: "#F5F0E7", padding: 18 }, ledgerHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" }, ledgerBrand: { color: "#25313B", fontSize: 10, fontWeight: "900", letterSpacing: 0.8 }, ledgerDate: { color: "#6E716E", fontSize: 12, marginTop: 6 }, ledgerStamp: { width: 55, height: 55, borderWidth: 2, borderColor: "#E24A3B", alignItems: "center", justifyContent: "center", transform: [{ rotate: "-8deg" }] }, ledgerStampText: { color: "#E24A3B", fontSize: 10, fontWeight: "900", textAlign: "center" }, ledgerCalendar: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 15, borderBottomWidth: 1, borderColor: "#C9C0B1" }, ledgerCalendarDay: { alignItems: "center", gap: 5 }, ledgerCalendarText: { color: "#5F615E", fontSize: 10, fontWeight: "800" }, ledgerCalendarMark: { width: 14, height: 6 }, ledgerTableHead: { flexDirection: "row", paddingVertical: 12, borderBottomWidth: 1, borderColor: "#25313B" }, ledgerHeadText: { color: "#4F504D", fontWeight: "900", fontSize: 8, textAlign: "center" }, ledgerTable: { borderBottomWidth: 1, borderColor: "#C9C0B1" }, ledgerRow: { height: 48, flexDirection: "row", alignItems: "center", borderBottomWidth: 1, borderColor: "#DDD4C6" }, ledgerMarker: { width: 4, height: 28, marginRight: 8 }, ledgerName: { color: "#25313B", fontSize: 13, fontWeight: "800" }, ledgerCell: { color: "#25313B", fontSize: 12, fontWeight: "800", width: 45, textAlign: "center" }, ledgerChart: { marginTop: 22 }, ledgerChartLabels: { flexDirection: "row", justifyContent: "space-between" }, ledgerChartTitle: { color: "#25313B", fontSize: 10, fontWeight: "900" }, ledgerChartValue: { color: "#E24A3B", fontSize: 15, fontWeight: "900" }, ledgerChartLine: { height: 96, marginTop: 10, borderLeftWidth: 1, borderBottomWidth: 1, borderColor: "#B6AE9E", position: "relative" }, ledgerPoint: { position: "absolute", width: 11, height: 11, borderRadius: 6, backgroundColor: "#2155CD" }, ledgerTrend: { position: "absolute", left: "9%", bottom: "29%", width: "72%", height: 2, backgroundColor: "#2155CD", transform: [{ rotate: "-17deg" }], transformOrigin: "left" },
});
