import { Linking, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import { Image } from "expo-image";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { getExercise } from "@/lib/workout-data";

export default function ExerciseDetail() { const colors = useColors(); const { id } = useLocalSearchParams<{ id: string }>(); const exercise = getExercise(id ?? "bench-press"); if (!exercise) return null; return <ScreenContainer edges={["top", "left", "right", "bottom"]} containerClassName="bg-background"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><View style={styles.nav}><Pressable onPress={() => router.back()}><IconSymbol name="chevron.left" size={27} color={colors.foreground} /></Pressable><Text style={[styles.navTitle, { color: colors.foreground }]}>Упражнение</Text><View style={{ width: 27 }} /></View><Image source={exercise.image} contentFit="cover" style={styles.hero} /><View style={[styles.tag, { backgroundColor: colors.primary + "25" }]}><Text style={[styles.tagText, { color: colors.primary }]}>{exercise.group}  ·  {exercise.equipment}</Text></View><Text style={[styles.title, { color: colors.foreground }]}>{exercise.name}</Text><Text style={[styles.description, { color: colors.muted }]}>{exercise.description}</Text><View style={[styles.recordCard, { backgroundColor: colors.surface, borderColor: colors.border }]}><View><Text style={[styles.recordLabel, { color: colors.muted }]}>ЛИЧНЫЙ РЕКОРД</Text><Text style={[styles.recordValue, { color: colors.foreground }]}>{exercise.recordKg ? `${exercise.recordKg} кг` : `${exercise.recordReps} сек`}</Text><Text style={[styles.recordSub, { color: colors.muted }]}>лучший результат · {exercise.recordReps} повторов</Text></View><IconSymbol name="trophy" size={30} color="#FF9F43" /></View><Text style={[styles.section, { color: colors.foreground }]}>Видео с техникой</Text><Pressable onPress={() => Linking.openURL(exercise.videoUrl)} style={[styles.video, { backgroundColor: colors.surface }]}><Image source={exercise.image} contentFit="cover" style={StyleSheet.absoluteFillObject} /><View style={styles.overlay} /><View style={styles.play}><IconSymbol name="play.fill" size={22} color="#101412" /></View><Text style={styles.videoText}>Смотреть вариант выполнения</Text></Pressable><Pressable onPress={() => router.push({ pathname: "/program/new", params: { exerciseId: exercise.id } })} style={({ pressed }) => [styles.primaryButton, { backgroundColor: colors.primary }, pressed && { opacity: 0.85 }]}><Text style={styles.primaryText}>＋  Добавить в программу</Text></Pressable></ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ content: { padding: 18, gap: 13 }, nav: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 4 }, navTitle: { fontSize: 16, fontWeight: "800" }, hero: { width: "100%", height: 225, borderRadius: 22 }, tag: { alignSelf: "flex-start", paddingHorizontal: 11, paddingVertical: 7, borderRadius: 10, marginTop: 2 }, tagText: { fontSize: 11, fontWeight: "800" }, title: { fontSize: 28, fontWeight: "800", lineHeight: 33, marginTop: 2 }, description: { fontSize: 14, lineHeight: 21 }, recordCard: { borderRadius: 18, borderWidth: 1, padding: 15, flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 4 }, recordLabel: { fontSize: 10, fontWeight: "800", letterSpacing: 1 }, recordValue: { fontSize: 25, fontWeight: "800", marginTop: 4 }, recordSub: { fontSize: 11, marginTop: 3 }, section: { fontSize: 19, fontWeight: "800", marginTop: 6 }, video: { height: 150, borderRadius: 18, overflow: "hidden", justifyContent: "flex-end", padding: 15 }, overlay: { ...StyleSheet.absoluteFillObject, backgroundColor: "#10141288" }, play: { alignSelf: "center", position: "absolute", top: 47, width: 51, height: 51, borderRadius: 26, backgroundColor: "#C8F169", alignItems: "center", justifyContent: "center" }, videoText: { color: "#F4F7F2", fontSize: 14, fontWeight: "800" }, primaryButton: { borderRadius: 16, paddingVertical: 16, alignItems: "center", marginTop: 2 }, primaryText: { color: "#101412", fontWeight: "800", fontSize: 15 } });
