import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { useWorkoutStore } from "@/lib/workout-store";
import { getExercise, isTimeBasedExercise } from "@/lib/workout-data";
import { groupWorkoutHistoryExercises } from "@/lib/workout-history";

export default function WorkoutHistoryExerciseScreen() {
  const colors = useColors(); const { workoutId, exerciseId } = useLocalSearchParams<{ workoutId: string; exerciseId: string }>(); const { completed } = useWorkoutStore();
  const workout = completed.find((item) => item.id === workoutId); const exercise = workout ? groupWorkoutHistoryExercises(workout).find((item) => item.exerciseId === exerciseId) : undefined; const definition = getExercise(exerciseId); const isTimed = isTimeBasedExercise(definition);
  return <ScreenContainer edges={["top", "left", "right", "bottom"]} className="px-5"><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={() => router.back()}><IconSymbol name="chevron.left" size={27} color={colors.foreground} /></Pressable><Text style={[styles.headerTitle, { color: colors.foreground }]}>Подходы</Text><View style={{ width: 27 }} /></View><View style={[styles.hero, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.eyebrow, { color: colors.primary }]}>ТОЛЬКО ПРОСМОТР</Text><Text style={[styles.title, { color: colors.foreground }]}>{definition?.name ?? exerciseId}</Text><Text style={[styles.subtitle, { color: colors.muted }]}>{definition?.group ?? "Упражнение"} · {exercise?.sets.length ?? 0} подходов</Text></View><View style={[styles.tableHeader, { borderBottomColor: colors.border }]}><Text style={[styles.tableLabel, { color: colors.muted, flex: 0.7 }]}>№</Text><Text style={[styles.tableLabel, { color: colors.muted, flex: isTimed ? 2.3 : 1.2 }]}>{isTimed ? "Минуты" : "Повторы"}</Text>{!isTimed && <Text style={[styles.tableLabel, { color: colors.muted, flex: 1.1, textAlign: "right" }]}>Вес</Text>}</View>{exercise?.sets.map((set, index) => <View key={`${set.weight}-${set.reps}-${index}`} style={[styles.setRow, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.setIndex, { color: colors.primary, flex: 0.7 }]}>{index + 1}</Text><Text style={[styles.setValue, { color: colors.foreground, flex: isTimed ? 2.3 : 1.2 }]}>{isTimed ? `${set.reps} мин` : set.reps}</Text>{!isTimed && <Text style={[styles.setValue, { color: colors.foreground, flex: 1.1, textAlign: "right" }]}>{set.weight} кг</Text>}</View>) ?? <Text style={[styles.empty, { color: colors.muted }]}>Подходи не найдены.</Text>}<Text style={[styles.readOnly, { color: colors.muted }]}>Это сохранённая история: её нельзя редактировать.</Text></ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingTop: 16, paddingBottom: 32, gap: 9 }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, headerTitle: { fontSize: 16, fontWeight: "900" }, hero: { borderWidth: 1, borderRadius: 19, padding: 15, gap: 5 }, eyebrow: { fontSize: 10, fontWeight: "900", letterSpacing: 0.8 }, title: { fontSize: 22, fontWeight: "900" }, subtitle: { fontSize: 12 }, tableHeader: { flexDirection: "row", paddingHorizontal: 12, paddingTop: 12, paddingBottom: 7, borderBottomWidth: 1 }, tableLabel: { fontSize: 10, fontWeight: "900", letterSpacing: 0.5 }, setRow: { minHeight: 55, borderWidth: 1, borderRadius: 14, paddingHorizontal: 13, flexDirection: "row", alignItems: "center" }, setIndex: { fontSize: 15, fontWeight: "900" }, setValue: { fontSize: 15, fontWeight: "900" }, readOnly: { textAlign: "center", fontSize: 11, marginTop: 8 }, empty: { textAlign: "center", marginVertical: 30 } });
