import { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { calculateBarbellPlateLayout, formatPlateLayout } from "@/lib/workout-data";
import { useWorkoutStore } from "@/lib/workout-store";

const plateOptions = [25, 20, 15, 10, 5, 2.5, 1.25, 0.5];

export default function BarbellScreen() {
  const colors = useColors();
  const { barbellProfile, setBarbellProfile } = useWorkoutStore();
  const [target, setTarget] = useState("80");
  const layout = calculateBarbellPlateLayout(Number(target) || barbellProfile.barWeightKg, barbellProfile);
  const togglePlate = (plate: number) => setBarbellProfile({ ...barbellProfile, availablePlatesKg: barbellProfile.availablePlatesKg.includes(plate) ? barbellProfile.availablePlatesKg.filter((value) => value !== plate) : [...barbellProfile.availablePlatesKg, plate].sort((a, b) => b - a) });
  return <ScreenContainer edges={["top", "left", "right", "bottom"]} className="px-5" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={() => router.back()}><IconSymbol name="chevron.left" size={27} color={colors.foreground} /></Pressable><Text style={[styles.headerTitle, { color: colors.foreground }]}>Профиль штанги</Text><View style={{ width: 27 }} /></View><Text style={[styles.eyebrow, { color: colors.primary }]}>РАСКЛАДКА БЛИНОВ</Text><Text style={[styles.title, { color: colors.foreground }]}>Целевой вес</Text><TextInput value={target} onChangeText={setTarget} keyboardType="decimal-pad" style={[styles.targetInput, { color: colors.foreground, borderColor: colors.primary }]} placeholder="80" placeholderTextColor={colors.muted} /><Text style={[styles.section, { color: colors.foreground }]}>Вес грифа</Text><View style={styles.choices}>{[15, 20].map((weight) => <Pressable key={weight} onPress={() => setBarbellProfile({ ...barbellProfile, barWeightKg: weight })} style={[styles.choice, { backgroundColor: barbellProfile.barWeightKg === weight ? colors.primary : colors.surface, borderColor: barbellProfile.barWeightKg === weight ? colors.primary : colors.border }]}><Text style={{ color: barbellProfile.barWeightKg === weight ? "#101412" : colors.foreground, fontWeight: "800" }}>{weight} кг</Text></Pressable>)}</View><Text style={[styles.section, { color: colors.foreground }]}>Доступные блины</Text><Text style={[styles.help, { color: colors.muted }]}>Выбери номиналы, которые есть в зале. Каждый блины ставятся симметрично на обе стороны.</Text><View style={styles.plates}>{plateOptions.map((plate) => { const active = barbellProfile.availablePlatesKg.includes(plate); return <Pressable key={plate} onPress={() => togglePlate(plate)} style={[styles.plate, { backgroundColor: active ? colors.primary : colors.surface, borderColor: active ? colors.primary : colors.border }]}><Text style={{ color: active ? "#101412" : colors.foreground, fontWeight: "800" }}>{plate}</Text></Pressable>; })}</View><View style={[styles.result, { backgroundColor: colors.surface, borderColor: colors.primary }]}><Text style={[styles.resultLabel, { color: colors.primary }]}>НА КАЖДУЮ СТОРОНУ</Text><Text style={[styles.resultWeight, { color: colors.foreground }]}>{formatPlateLayout(layout.perSide)} кг</Text><Text style={[styles.resultMeta, { color: colors.muted }]}>Фактический вес: {layout.loadedWeightKg.toFixed(1)} кг{layout.differenceKg ? ` · недобор ${layout.differenceKg.toFixed(1)} кг` : " · точное совпадение"}</Text></View></ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { paddingTop: 16, paddingBottom: 34, gap: 13 }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, headerTitle: { fontSize: 16, fontWeight: "800" }, eyebrow: { fontSize: 11, fontWeight: "900", letterSpacing: 1.2, marginTop: 15 }, title: { fontSize: 28, fontWeight: "800", marginTop: 5 }, targetInput: { height: 62, borderWidth: 1, borderRadius: 17, paddingHorizontal: 18, fontSize: 26, fontWeight: "900", marginTop: 4 }, section: { fontSize: 18, fontWeight: "800", marginTop: 13 }, choices: { flexDirection: "row", gap: 9 }, choice: { flex: 1, minHeight: 47, borderRadius: 13, borderWidth: 1, alignItems: "center", justifyContent: "center" }, help: { fontSize: 12, lineHeight: 18, marginTop: -6 }, plates: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, plate: { width: "22.5%", minHeight: 43, borderRadius: 12, borderWidth: 1, alignItems: "center", justifyContent: "center" }, result: { borderRadius: 18, borderWidth: 1, padding: 16, marginTop: 8 }, resultLabel: { fontSize: 10, fontWeight: "900", letterSpacing: 1 }, resultWeight: { fontSize: 24, fontWeight: "900", marginTop: 7 }, resultMeta: { fontSize: 12, marginTop: 7 } });
