import { useCallback, useEffect, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import Constants from "expo-constants";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { isErrorReportingConfigured, reportException } from "@/lib/error-reporting";
import { clearLaunchDiagnostics, getLaunchDiagnostics, recordLaunchDiagnostic, type LaunchDiagnostic } from "@/lib/launch-diagnostics";

export default function DiagnosticsScreen() {
  const colors = useColors();
  const [entries, setEntries] = useState<LaunchDiagnostic[]>([]);
  const refresh = useCallback(async () => { setEntries(await getLaunchDiagnostics()); }, []);
  useEffect(() => { void recordLaunchDiagnostic("Открыт экран диагностики"); void refresh(); }, [refresh]);
  const sendTest = () => { reportException(new Error("Проверочное событие диагностики"), { source: "diagnostics-screen" }); void recordLaunchDiagnostic("Отправлено проверочное событие Sentry", "info"); Alert.alert("Событие отправлено", "Проверочное событие будет видно в Sentry, если DSN настроен."); void refresh(); };
  const clear = async () => { await clearLaunchDiagnostics(); await refresh(); };
  const sentryReady = isErrorReportingConfigured();
  const appVersion = Constants.expoConfig?.version ?? "неизвестно";

  return <ScreenContainer edges={["top", "left", "right", "bottom"]} className="px-5" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><IconSymbol name="chevron.left" size={27} color={colors.foreground} /></Pressable><Text style={[styles.headerTitle, { color: colors.foreground }]}>Диагностика</Text><View style={styles.back} /></View><View style={[styles.hero, { backgroundColor: colors.primary }]}><Text style={styles.heroEyebrow}>СОСТОЯНИЕ ЗАПУСКА</Text><Text style={styles.heroTitle}>Проверка системы</Text><Text style={styles.heroText}>Здесь сохраняются ключевые этапы загрузки и ошибки, чтобы быстрее находить причину сбоев.</Text></View><View style={styles.grid}><StatusCard title="Отчёты Sentry" value={sentryReady ? "Подключены" : "Не настроены"} ok={sentryReady} colors={colors} /><StatusCard title="Версия приложения" value={appVersion} ok colors={colors} /><StatusCard title="Журнал запуска" value={`${entries.length} записей`} ok colors={colors} /></View><View style={[styles.actions, { backgroundColor: colors.surface, borderColor: colors.border }]}><Pressable onPress={() => void refresh()} style={[styles.primary, { backgroundColor: colors.primary }]}><Text style={styles.primaryText}>Обновить проверку</Text></Pressable><Pressable onPress={sendTest} disabled={!sentryReady} style={[styles.secondary, { borderColor: colors.border, opacity: sentryReady ? 1 : 0.5 }]}><Text style={[styles.secondaryText, { color: colors.foreground }]}>Отправить тест в Sentry</Text></Pressable><Pressable onPress={() => void clear()}><Text style={[styles.clear, { color: colors.muted }]}>Очистить локальный журнал</Text></Pressable></View><Text style={[styles.sectionTitle, { color: colors.foreground }]}>Последние события</Text>{entries.length ? entries.map((entry) => <View key={entry.id} style={[styles.event, { backgroundColor: colors.surface, borderColor: entry.level === "error" ? colors.error : colors.border }]}><View style={[styles.levelDot, { backgroundColor: entry.level === "error" ? colors.error : entry.level === "warning" ? colors.warning : colors.success }]} /><View style={{ flex: 1 }}><Text style={[styles.eventStage, { color: colors.foreground }]}>{entry.stage}</Text>{entry.detail && <Text style={[styles.eventDetail, { color: colors.muted }]}>{entry.detail}</Text>}<Text style={[styles.eventTime, { color: colors.muted }]}>{new Date(entry.at).toLocaleString("ru-RU")}</Text></View></View>) : <View style={[styles.empty, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.emptyText, { color: colors.muted }]}>Журнал пока пуст. Он заполнится при следующем запуске приложения.</Text></View>}</ScrollView></ScreenContainer>;
}

function StatusCard({ title, value, ok, colors }: { title: string; value: string; ok: boolean; colors: ReturnType<typeof useColors> }) { return <View style={[styles.status, { backgroundColor: colors.surface, borderColor: ok ? colors.border : colors.warning + "55" }]}><Text style={[styles.statusTitle, { color: colors.muted }]}>{title}</Text><Text style={[styles.statusValue, { color: ok ? colors.foreground : colors.warning }]}>{value}</Text></View>; }

const styles = StyleSheet.create({ content: { paddingTop: 12, paddingBottom: 36, gap: 12 }, header: { minHeight: 44, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, back: { width: 36, height: 36, alignItems: "center", justifyContent: "center" }, headerTitle: { fontSize: 16, fontWeight: "900" }, hero: { borderRadius: 22, padding: 20, gap: 7 }, heroEyebrow: { color: "#101412AA", fontSize: 10, fontWeight: "900", letterSpacing: 1 }, heroTitle: { color: "#101412", fontSize: 25, fontWeight: "900" }, heroText: { color: "#101412CC", fontSize: 13, lineHeight: 19 }, grid: { flexDirection: "row", gap: 8 }, status: { flex: 1, minHeight: 84, borderWidth: 1, borderRadius: 16, padding: 10, justifyContent: "space-between" }, statusTitle: { fontSize: 10, lineHeight: 13, fontWeight: "700" }, statusValue: { fontSize: 13, lineHeight: 17, fontWeight: "900" }, actions: { borderWidth: 1, borderRadius: 18, padding: 13, gap: 9 }, primary: { minHeight: 48, borderRadius: 13, alignItems: "center", justifyContent: "center" }, primaryText: { color: "#101412", fontSize: 13, fontWeight: "900" }, secondary: { minHeight: 45, borderWidth: 1, borderRadius: 13, alignItems: "center", justifyContent: "center" }, secondaryText: { fontSize: 12, fontWeight: "900" }, clear: { textAlign: "center", fontSize: 11, fontWeight: "800", paddingVertical: 4 }, sectionTitle: { fontSize: 19, fontWeight: "900", marginTop: 4 }, event: { minHeight: 72, borderWidth: 1, borderRadius: 16, padding: 12, flexDirection: "row", gap: 9 }, levelDot: { width: 8, height: 8, borderRadius: 4, marginTop: 5 }, eventStage: { fontSize: 13, fontWeight: "900" }, eventDetail: { fontSize: 11, lineHeight: 16, marginTop: 3 }, eventTime: { fontSize: 10, marginTop: 5 }, empty: { borderWidth: 1, borderRadius: 16, padding: 16 }, emptyText: { fontSize: 12, lineHeight: 18 } });
