import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import Svg, { Line, Rect } from "react-native-svg";
import { router } from "expo-router";

import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { useNutritionStore } from "@/lib/nutrition-store";
import { buildWeeklyNutritionReport, type WeeklyNutritionPoint } from "@/lib/nutrition-weekly-report";

export default function NutritionReportScreen() {
  const colors = useColors();
  const { entries, dailyCalorieGoal, dailyMacroGoals } = useNutritionStore();
  const points = buildWeeklyNutritionReport(entries);
  const totalCalories = points.reduce((sum, point) => sum + point.calories, 0);
  const weeklyMacros = points.reduce((sum, point) => ({ protein: sum.protein + point.macros.protein, fat: sum.fat + point.macros.fat, carbs: sum.carbs + point.macros.carbs }), { protein: 0, fat: 0, carbs: 0 });
  const daysWithFood = points.filter((point) => point.calories > 0).length;

  return <ScreenContainer edges={["top", "left", "right", "bottom"]} className="px-5" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.header}><Pressable onPress={() => router.back()} style={[styles.back, { borderColor: colors.border }]}><IconSymbol name="chevron.left" size={24} color={colors.foreground} /></Pressable><View style={{ flex: 1 }}><Text style={[styles.eyebrow, { color: colors.primary }]}>ПИТАНИЕ · 7 ДНЕЙ</Text><Text style={[styles.title, { color: colors.foreground }]}>Недельный отчёт</Text></View></View>
    <View style={[styles.summary, { backgroundColor: colors.surface, borderColor: colors.border }]}><View><Text style={[styles.summaryValue, { color: colors.foreground }]}>{totalCalories.toLocaleString("ru-RU")}</Text><Text style={[styles.summaryCaption, { color: colors.muted }]}>ККАЛ ЗА 7 ДНЕЙ</Text></View><View style={styles.summarySide}><Text style={[styles.summaryValueSmall, { color: colors.primary }]}>{daysWithFood}/7</Text><Text style={[styles.summaryCaption, { color: colors.muted }]}>ДНЕЙ С ЗАПИСЯМИ</Text></View></View>
    <View style={[styles.chartCard, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.chartHeading}><View><Text style={[styles.chartTitle, { color: colors.foreground }]}>КАЛОРИИ ПО ДНЯМ</Text><Text style={[styles.chartHint, { color: colors.muted }]}>План: {dailyCalorieGoal} ккал в день</Text></View><Text style={[styles.chartBadge, { color: colors.primary }]}>{Math.round(totalCalories / 7)} СР.</Text></View><CaloriesChart points={points} goal={dailyCalorieGoal} colors={colors} /></View>
    <View style={[styles.chartCard, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.chartHeading}><View><Text style={[styles.chartTitle, { color: colors.foreground }]}>БЖУ ПО ДНЯМ</Text><Text style={[styles.chartHint, { color: colors.muted }]}>Граммы на каждый из последних 7 дней</Text></View></View><MacroWeekChart points={points} colors={colors} /></View>
    <View style={[styles.macroTotals, { backgroundColor: colors.surface, borderColor: colors.border }]}>{([{ key: "protein", short: "Б", name: "БЕЛКИ", color: colors.primary }, { key: "fat", short: "Ж", name: "ЖИРЫ", color: "#2F5FC4" }, { key: "carbs", short: "У", name: "УГЛЕВОДЫ", color: "#E6A52D" }] as const).map((item) => <View key={item.key} style={[styles.macroTotal, { borderRightColor: colors.border }]}><Text style={[styles.macroTotalShort, { color: item.color }]}>{item.short}</Text><Text style={[styles.macroTotalValue, { color: colors.foreground }]}>{weeklyMacros[item.key]} г</Text><Text style={[styles.macroTotalCaption, { color: colors.muted }]}>{item.name} · ЦЕЛЬ {dailyMacroGoals[item.key] * 7} Г</Text></View>)}</View>
    <Text style={[styles.note, { color: colors.muted }]}>Отчёт строится только по локально сохранённым записям питания. Нулевые дни не скрываются, чтобы динамика была честной.</Text>
  </ScrollView></ScreenContainer>;
}

function CaloriesChart({ points, goal, colors }: { points: WeeklyNutritionPoint[]; goal: number; colors: any }) {
  const width = 326; const height = 170; const baseline = 132; const left = 10; const chartWidth = 306; const maximum = Math.max(goal, ...points.map((point) => point.calories), 1); const goalY = baseline - (goal / maximum) * 94; const barWidth = 27; const gap = (chartWidth - barWidth * 7) / 6;
  return <><Svg width="100%" height={height} viewBox={`0 0 ${width} ${height}`}><Line x1={left} x2={width - left} y1={baseline} y2={baseline} stroke={colors.border} strokeWidth="1" /><Line x1={left} x2={width - left} y1={goalY} y2={goalY} stroke={colors.primary} strokeWidth="1" strokeDasharray="4 4" />{points.map((point, index) => { const barHeight = (point.calories / maximum) * 94; const x = left + index * (barWidth + gap); return <Rect key={point.date} x={x} y={baseline - barHeight} width={barWidth} height={barHeight} fill={point.calories > goal ? colors.error : index === points.length - 1 ? "#2F5FC4" : colors.foreground} />; })}</Svg><View style={styles.axis}>{points.map((point) => <Text key={point.date} style={[styles.axisText, { color: colors.muted }]}>{point.label}</Text>)}</View></>;
}

function MacroWeekChart({ points, colors }: { points: WeeklyNutritionPoint[]; colors: any }) {
  const rows = [{ key: "protein", label: "БЕЛКИ", color: colors.primary }, { key: "fat", label: "ЖИРЫ", color: "#2F5FC4" }, { key: "carbs", label: "УГЛЕВОДЫ", color: "#E6A52D" }] as const;
  return <View style={styles.macroRows}>{rows.map((row) => { const values = points.map((point) => point.macros[row.key]); const max = Math.max(1, ...values); return <View key={row.key} style={styles.macroRow}><Text style={[styles.macroRowLabel, { color: row.color }]}>{row.label}</Text><View style={styles.macroBars}>{values.map((value, index) => <View key={`${row.key}-${points[index].date}`} style={[styles.macroBarTrack, { backgroundColor: colors.border }]}><View style={[styles.macroBar, { height: `${Math.max(value ? 8 : 0, Math.round((value / max) * 100))}%`, backgroundColor: row.color }]} /></View>)}</View></View>; })}</View>;
}

const styles = StyleSheet.create({ content:{paddingTop:14,paddingBottom:32,gap:12},header:{flexDirection:"row",alignItems:"center",gap:10},back:{width:42,height:42,borderWidth:1,alignItems:"center",justifyContent:"center"},eyebrow:{fontSize:10,fontWeight:"900",letterSpacing:1},title:{fontSize:29,fontWeight:"900",letterSpacing:-1,marginTop:3},summary:{borderWidth:1,borderLeftWidth:6,padding:15,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},summaryValue:{fontSize:34,fontWeight:"900",letterSpacing:-2},summaryValueSmall:{fontSize:27,fontWeight:"900",textAlign:"right"},summaryCaption:{fontSize:9,fontWeight:"900",letterSpacing:.4,marginTop:3},summarySide:{alignItems:"flex-end"},chartCard:{borderWidth:1,padding:13,gap:10},chartHeading:{flexDirection:"row",justifyContent:"space-between",alignItems:"flex-start"},chartTitle:{fontSize:13,fontWeight:"900",letterSpacing:.4},chartHint:{fontSize:10,fontWeight:"800",marginTop:3},chartBadge:{fontSize:11,fontWeight:"900"},axis:{flexDirection:"row",justifyContent:"space-between",paddingHorizontal:10},axisText:{fontSize:9,fontWeight:"900",width:27,textAlign:"center"},macroRows:{gap:13},macroRow:{gap:5},macroRowLabel:{fontSize:9,fontWeight:"900",letterSpacing:.5},macroBars:{height:60,flexDirection:"row",gap:5,alignItems:"flex-end"},macroBarTrack:{flex:1,height:"100%",justifyContent:"flex-end"},macroBar:{width:"100%"},macroTotals:{borderWidth:1,flexDirection:"row"},macroTotal:{flex:1,padding:10,borderRightWidth:StyleSheet.hairlineWidth,gap:2},macroTotalShort:{fontSize:13,fontWeight:"900"},macroTotalValue:{fontSize:18,fontWeight:"900",letterSpacing:-.6},macroTotalCaption:{fontSize:8,fontWeight:"900",lineHeight:11},note:{fontSize:10,lineHeight:15,textAlign:"center",paddingHorizontal:14} });
