import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { getCurrentTrainingPeriodStats, getMonthComparisonStats, type TrainingPeriodStats } from "@/lib/workout-data";
import { useWorkoutStore } from "@/lib/workout-store";

function volumeLabel(volume: number) { return volume >= 1000 ? `${(volume / 1000).toFixed(1)} т` : `${Math.round(volume)} кг`; }
function percent(value: number, max: number) { return max > 0 ? Math.max(6, Math.round((value / max) * 100)) : 6; }

function PeriodCard({ title, stats, color, muted }: { title: string; stats: TrainingPeriodStats; color: string; muted: string }) {
  return <View style={[styles.periodCard, { backgroundColor: color + "16", borderColor: color + "45" }]}><Text style={[styles.periodTitle, { color }]}>{title}</Text><View style={styles.periodMetrics}><Metric value={String(stats.workoutCount)} label="тренировок" color={color} muted={muted} /><Metric value={volumeLabel(stats.totalVolume)} label="объём" color={color} muted={muted} /><Metric value={String(stats.durationMinutes)} label="минут" color={color} muted={muted} /></View><Text style={[styles.periodHint, { color: muted }]}>{stats.activeDays ? `${stats.activeDays} активн. ${stats.activeDays === 1 ? "день" : "дней"}` : "Пока нет завершённых тренировок"}</Text></View>;
}

function Metric({ value, label, color, muted }: { value: string; label: string; color: string; muted: string }) { return <View><Text style={[styles.metricValue, { color }]}>{value}</Text><Text style={[styles.metricLabel, { color: muted }]}>{label}</Text></View>; }

function SettingToggle({ title, description, enabled, onPress, color, muted, foreground, symbol }: { title: string; description: string; enabled: boolean; onPress: () => void; color: string; muted: string; foreground: string; symbol: string }) {
  return <Pressable onPress={onPress} style={({ pressed }) => [styles.setting, { backgroundColor: color + "0A", borderColor: enabled ? color : color + "28" }, pressed && { opacity: 0.72 }]}><View style={[styles.settingIcon, { backgroundColor: enabled ? color + "20" : color + "0B" }]}><Text style={{ color: enabled ? color : muted, fontSize: 18 }}>{symbol}</Text></View><View style={{ flex: 1 }}><Text style={[styles.settingTitle, { color: foreground }]}>{title}</Text><Text style={[styles.settingDescription, { color: muted }]}>{description}</Text></View><View style={[styles.toggle, { backgroundColor: enabled ? color : "#3D4050" }]}><View style={[styles.thumb, { alignSelf: enabled ? "flex-end" : "flex-start" }]} /></View></Pressable>;
}

function MonthComparisonChart({ current, previous, primary, muted, foreground }: { current: TrainingPeriodStats; previous: TrainingPeriodStats; primary: string; muted: string; foreground: string }) {
  const rows = [{ label: "Тренировки", current: current.workoutCount, previous: previous.workoutCount, currentValue: String(current.workoutCount), previousValue: String(previous.workoutCount) }, { label: "Объём", current: current.totalVolume, previous: previous.totalVolume, currentValue: volumeLabel(current.totalVolume), previousValue: volumeLabel(previous.totalVolume) }, { label: "Время", current: current.durationMinutes, previous: previous.durationMinutes, currentValue: `${current.durationMinutes} мин`, previousValue: `${previous.durationMinutes} мин` }];
  return <View style={[styles.chartCard, { backgroundColor: primary + "0A" }]}><View style={styles.chartLegend}><View style={styles.legendItem}><View style={[styles.legendDot, { backgroundColor: primary }]} /><Text style={[styles.legendText, { color: muted }]}>Текущий</Text></View><View style={styles.legendItem}><View style={[styles.legendDot, { backgroundColor: "#FF9F43" }]} /><Text style={[styles.legendText, { color: muted }]}>Предыдущий</Text></View></View>{rows.map((row) => { const max = Math.max(row.current, row.previous); return <View key={row.label} style={styles.chartRow}><View style={styles.chartRowHeader}><Text style={[styles.chartLabel, { color: foreground }]}>{row.label}</Text><Text style={[styles.chartValues, { color: muted }]}>{row.currentValue} / {row.previousValue}</Text></View><View style={styles.barPair}><View style={[styles.barTrack, { backgroundColor: primary + "12" }]}><View style={[styles.bar, { width: `${percent(row.current, max)}%`, backgroundColor: primary }]} /></View><View style={[styles.barTrack, { backgroundColor: "#FF9F4318" }]}><View style={[styles.bar, { width: `${percent(row.previous, max)}%`, backgroundColor: "#FF9F43" }]} /></View></View></View>; })}</View>;
}

export default function ProfileScreen() {
  const colors = useColors();
  const { completed, restTimerSoundEnabled, restTimerVibrationEnabled, setRestTimerSoundEnabled, setRestTimerVibrationEnabled } = useWorkoutStore();
  const periods = getCurrentTrainingPeriodStats(completed);
  const comparison = getMonthComparisonStats(completed);
  return <ScreenContainer edges={["top", "left", "right", "bottom"]} className="px-5" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={() => router.back()}><IconSymbol name="chevron.left" size={27} color={colors.foreground} /></Pressable><Text style={[styles.headerTitle, { color: colors.foreground }]}>Личный кабинет</Text><Pressable onPress={() => router.push("/settings")}><IconSymbol name="gearshape" size={21} color={colors.foreground} /></Pressable></View><Text style={[styles.eyebrow, { color: colors.primary }]}>ВАШ ПРОГРЕСС</Text><Text style={[styles.title, { color: colors.foreground }]}>Тренировки и отдых</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Сводка обновляется после завершения каждой тренировки.</Text><PeriodCard title="Эта неделя" stats={periods.week} color={colors.primary} muted={colors.muted} /><PeriodCard title="Этот месяц" stats={periods.month} color="#FF9F43" muted={colors.muted} /><Text style={[styles.sectionTitle, { color: colors.foreground }]}>Месяц к месяцу</Text><Text style={[styles.sectionHint, { color: colors.muted }]}>Текущий месяц сравнивается с предыдущим по трём ключевым показателям.</Text><MonthComparisonChart current={comparison.current} previous={comparison.previous} primary={colors.primary} muted={colors.muted} foreground={colors.foreground} /><Text style={[styles.sectionTitle, { color: colors.foreground }]}>Таймер отдыха</Text><SettingToggle title="Звуковой сигнал" description={restTimerSoundEnabled ? "«Отдых окончен» прозвучит при нулевом таймере." : "Таймер завершится без звукового сигнала."} enabled={restTimerSoundEnabled} onPress={() => setRestTimerSoundEnabled(!restTimerSoundEnabled)} color={colors.primary} muted={colors.muted} foreground={colors.foreground} symbol="♪" /><SettingToggle title="Вибрация" description={restTimerVibrationEnabled ? "Короткое подтверждение дополняет сигнал окончания отдыха." : "Окончание отдыха будет без вибрации."} enabled={restTimerVibrationEnabled} onPress={() => setRestTimerVibrationEnabled(!restTimerVibrationEnabled)} color="#7BE495" muted={colors.muted} foreground={colors.foreground} symbol="≋" /><Text style={[styles.footnote, { color: colors.muted }]}>При ручном нажатии «Пропустить» ни звук, ни вибрация не запускаются.</Text></ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { paddingTop: 16, paddingBottom: 32, gap: 13 }, header: { minHeight: 40, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, headerTitle: { fontSize: 16, fontWeight: "900" }, eyebrow: { fontSize: 11, fontWeight: "900", letterSpacing: 1.1, marginTop: 8 }, title: { fontSize: 28, fontWeight: "900", marginTop: 3 }, subtitle: { fontSize: 12, lineHeight: 18 }, periodCard: { borderWidth: 1, borderRadius: 20, padding: 15, gap: 12 }, periodTitle: { fontSize: 14, fontWeight: "900" }, periodMetrics: { flexDirection: "row", justifyContent: "space-between" }, metricValue: { fontSize: 22, fontWeight: "900" }, metricLabel: { fontSize: 10, marginTop: 3 }, periodHint: { fontSize: 11 }, sectionTitle: { fontSize: 18, fontWeight: "900", marginTop: 7 }, sectionHint: { fontSize: 11, lineHeight: 16, marginTop: -5 }, chartCard: { backgroundColor: "#FFFFFF0A", borderRadius: 18, padding: 14, gap: 14 }, chartLegend: { flexDirection: "row", gap: 16 }, legendItem: { flexDirection: "row", alignItems: "center", gap: 5 }, legendDot: { width: 8, height: 8, borderRadius: 4 }, legendText: { fontSize: 10, fontWeight: "800" }, chartRow: { gap: 6 }, chartRowHeader: { flexDirection: "row", justifyContent: "space-between" }, chartLabel: { color: "#FFFFFF", fontSize: 12, fontWeight: "800" }, chartValues: { fontSize: 10 }, barPair: { gap: 4 }, barTrack: { height: 8, backgroundColor: "#FFFFFF0A", borderRadius: 4, overflow: "hidden" }, bar: { height: "100%", borderRadius: 4 }, setting: { borderWidth: 1, borderRadius: 18, padding: 13, flexDirection: "row", alignItems: "center", gap: 11 }, settingIcon: { width: 40, height: 40, borderRadius: 13, alignItems: "center", justifyContent: "center" }, settingTitle: { color: "#FFFFFF", fontSize: 14, fontWeight: "900" }, settingDescription: { fontSize: 11, lineHeight: 16, marginTop: 4 }, toggle: { width: 45, height: 26, borderRadius: 13, padding: 3 }, thumb: { width: 20, height: 20, borderRadius: 10, backgroundColor: "#FFFFFF" }, footnote: { fontSize: 11, lineHeight: 16, marginTop: -5 } });
