import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { getCurrentTrainingPeriodStats, type TrainingPeriodStats } from "@/lib/workout-data";
import { useWorkoutStore } from "@/lib/workout-store";

function volumeLabel(volume: number) { return volume >= 1000 ? `${(volume / 1000).toFixed(1)} т` : `${Math.round(volume)} кг`; }

function PeriodCard({ title, stats, color, muted }: { title: string; stats: TrainingPeriodStats; color: string; muted: string }) {
  return <View style={[styles.periodCard, { backgroundColor: color + "16", borderColor: color + "45" }]}><Text style={[styles.periodTitle, { color }]}>{title}</Text><View style={styles.periodMetrics}><View><Text style={[styles.metricValue, { color }]}>{stats.workoutCount}</Text><Text style={[styles.metricLabel, { color: muted }]}>тренировок</Text></View><View><Text style={[styles.metricValue, { color }]}>{volumeLabel(stats.totalVolume)}</Text><Text style={[styles.metricLabel, { color: muted }]}>объём</Text></View><View><Text style={[styles.metricValue, { color }]}>{stats.durationMinutes}</Text><Text style={[styles.metricLabel, { color: muted }]}>минут</Text></View></View><Text style={[styles.periodHint, { color: muted }]}>{stats.activeDays ? `${stats.activeDays} активн. ${stats.activeDays === 1 ? "день" : "дней"}` : "Пока нет завершённых тренировок"}</Text></View>;
}

export default function ProfileScreen() {
  const colors = useColors();
  const { completed, restTimerSoundEnabled, setRestTimerSoundEnabled } = useWorkoutStore();
  const periods = getCurrentTrainingPeriodStats(completed);
  return <ScreenContainer edges={["top", "left", "right", "bottom"]} className="px-5" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={() => router.back()}><IconSymbol name="chevron.left" size={27} color={colors.foreground} /></Pressable><Text style={[styles.headerTitle, { color: colors.foreground }]}>Личный кабинет</Text><Pressable onPress={() => router.push("/settings")}><IconSymbol name="gearshape" size={21} color={colors.foreground} /></Pressable></View><Text style={[styles.eyebrow, { color: colors.primary }]}>ВАШ ПРОГРЕСС</Text><Text style={[styles.title, { color: colors.foreground }]}>Тренировки и отдых</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Сводка обновляется после завершения каждой тренировки.</Text><PeriodCard title="Эта неделя" stats={periods.week} color={colors.primary} muted={colors.muted} /><PeriodCard title="Этот месяц" stats={periods.month} color="#FF9F43" muted={colors.muted} /><Text style={[styles.sectionTitle, { color: colors.foreground }]}>Таймер отдыха</Text><Pressable onPress={() => setRestTimerSoundEnabled(!restTimerSoundEnabled)} style={[styles.soundCard, { backgroundColor: colors.surface, borderColor: restTimerSoundEnabled ? colors.primary : colors.border }]}><View style={[styles.soundIcon, { backgroundColor: restTimerSoundEnabled ? colors.primary + "20" : colors.background }]}><Text style={{ color: restTimerSoundEnabled ? colors.primary : colors.muted, fontSize: 18 }}>{restTimerSoundEnabled ? "♪" : "×"}</Text></View><View style={{ flex: 1 }}><Text style={[styles.soundTitle, { color: colors.foreground }]}>Звуковой сигнал</Text><Text style={[styles.soundDescription, { color: colors.muted }]}>{restTimerSoundEnabled ? "«Отдых окончен» прозвучит при нулевом таймере." : "Таймер завершится без звукового сигнала."}</Text></View><View style={[styles.toggle, { backgroundColor: restTimerSoundEnabled ? colors.primary : colors.border }]}><View style={[styles.thumb, { alignSelf: restTimerSoundEnabled ? "flex-end" : "flex-start" }]} /></View></Pressable><Text style={[styles.footnote, { color: colors.muted }]}>При ручном нажатии «Пропустить» сигнал не воспроизводится.</Text></ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { paddingTop: 16, paddingBottom: 32, gap: 13 }, header: { minHeight: 40, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, headerTitle: { fontSize: 16, fontWeight: "900" }, eyebrow: { fontSize: 11, fontWeight: "900", letterSpacing: 1.1, marginTop: 8 }, title: { fontSize: 28, fontWeight: "900", marginTop: 3 }, subtitle: { fontSize: 12, lineHeight: 18 }, periodCard: { borderWidth: 1, borderRadius: 20, padding: 15, gap: 12 }, periodTitle: { fontSize: 14, fontWeight: "900" }, periodMetrics: { flexDirection: "row", justifyContent: "space-between" }, metricValue: { fontSize: 22, fontWeight: "900" }, metricLabel: { fontSize: 10, marginTop: 3 }, periodHint: { fontSize: 11 }, sectionTitle: { fontSize: 18, fontWeight: "900", marginTop: 7 }, soundCard: { borderWidth: 1, borderRadius: 18, padding: 13, flexDirection: "row", alignItems: "center", gap: 11 }, soundIcon: { width: 40, height: 40, borderRadius: 13, alignItems: "center", justifyContent: "center" }, soundTitle: { fontSize: 14, fontWeight: "900" }, soundDescription: { fontSize: 11, lineHeight: 16, marginTop: 4 }, toggle: { width: 45, height: 26, borderRadius: 13, padding: 3 }, thumb: { width: 20, height: 20, borderRadius: 10, backgroundColor: "#FFFFFF" }, footnote: { fontSize: 11, lineHeight: 16, marginTop: -5 } });
