import { useMemo } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { defaultPrograms, getExercise, getExerciseHistory, recommendWorkingWeight } from "@/lib/workout-data";
import { trpc } from "@/lib/trpc";
import { useWorkoutStore } from "@/lib/workout-store";

export default function RecommendationsScreen() {
  const colors = useColors();
  const { oneRmFormula, plateStepKg } = useWorkoutStore();
  const historyQuery = trpc.workoutHistory.all.useQuery();
  const historyByExercise = useMemo(() => { const grouped: Record<string, { date: string; sets: { weight: number; reps: number }[]; volume: number }[]> = {}; (historyQuery.data ?? []).forEach((row) => { const date = new Date(row.date).toISOString(); const entries = grouped[row.exerciseId] ?? (grouped[row.exerciseId] = []); let entry = entries.find((item) => item.date === date); if (!entry) { entry = { date, sets: [], volume: 0 }; entries.push(entry); } entry.sets.push({ weight: row.weightCentiKg / 100, reps: row.reps }); entry.volume += row.volumeCentiKg / 100; }); Object.values(grouped).forEach((items) => items.sort((a, b) => b.date.localeCompare(a.date))); return grouped; }, [historyQuery.data]);
  const program = defaultPrograms[0];
  return <ScreenContainer edges={["top", "left", "right", "bottom"]} className="px-5" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.header}><Pressable onPress={() => router.back()}><IconSymbol name="chevron.left" size={27} color={colors.foreground} /></Pressable><Text style={[styles.headerTitle, { color: colors.foreground }]}>Следующая тренировка</Text><View style={{ width: 27 }} /></View><Text style={[styles.eyebrow, { color: colors.primary }]}>ПРОЗРАЧНЫЕ РЕКОМЕНДАЦИИ</Text><Text style={[styles.title, { color: colors.foreground }]}>{program.name}</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Каждая рекомендация объясняет исходный подход, расчётный 1RM, цель и выбранный шаг округления.</Text>{program.exercises.map((item) => { const exercise = getExercise(item.exerciseId); const history = historyByExercise[item.exerciseId] ?? getExerciseHistory(item.exerciseId); const recommendation = recommendWorkingWeight({ history, targetReps: item.reps, incrementKg: plateStepKg, formula: oneRmFormula }); return <View key={item.exerciseId} style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.cardTop}><View style={{ flex: 1 }}><Text style={[styles.exerciseName, { color: colors.foreground }]}>{exercise?.name}</Text><Text style={[styles.plan, { color: colors.muted }]}>Цель: {item.sets} × {item.reps} повторов</Text></View><Text style={[styles.weight, { color: colors.primary }]}>{recommendation.weightKg ? `${recommendation.weightKg.toFixed(1)} кг` : "—"}</Text></View><Text style={[styles.reason, { color: colors.muted }]}>{recommendation.reason}</Text>{recommendation.latestWeightKg > 0 && <View style={[styles.explain, { backgroundColor: colors.background, borderColor: colors.border }]}><Text style={[styles.explainText, { color: colors.foreground }]}>Последний ориентир: {recommendation.latestWeightKg} кг × {recommendation.latestReps}</Text><Text style={[styles.explainText, { color: colors.foreground }]}>Расчётный 1RM: {recommendation.estimatedOneRmKg.toFixed(1)} кг</Text><Text style={[styles.explainText, { color: colors.foreground }]}>Рабочая интенсивность: до {recommendation.targetIntensityPercent}% 1RM · шаг {plateStepKg} кг</Text></View>}<View style={[styles.delta, { backgroundColor: recommendation.changeKg > 0 ? colors.primary + "18" : colors.background }]}><Text style={[styles.deltaText, { color: recommendation.changeKg > 0 ? colors.primary : colors.muted }]}>{recommendation.changeKg > 0 ? `+${recommendation.changeKg.toFixed(1)} кг к прошлому рабочему весу` : recommendation.changeKg < 0 ? `${recommendation.changeKg.toFixed(1)} кг для закрепления техники` : "Сохрани текущий рабочий вес"}</Text></View></View>; })}</ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingTop: 16, paddingBottom: 34, gap: 13 }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, headerTitle: { fontSize: 16, fontWeight: "800" }, eyebrow: { fontSize: 10, letterSpacing: 1, fontWeight: "900", marginTop: 15 }, title: { fontSize: 25, fontWeight: "800", marginTop: 4 }, subtitle: { fontSize: 12, lineHeight: 18 }, card: { borderRadius: 18, borderWidth: 1, padding: 14 }, cardTop: { flexDirection: "row", alignItems: "center", gap: 8 }, exerciseName: { fontSize: 15, fontWeight: "800" }, plan: { fontSize: 11, marginTop: 4 }, weight: { fontSize: 21, fontWeight: "900" }, reason: { fontSize: 12, lineHeight: 17, marginTop: 12 }, explain: { borderWidth: 1, borderRadius: 12, padding: 10, gap: 4, marginTop: 10 }, explainText: { fontSize: 11, lineHeight: 16 }, delta: { borderRadius: 10, paddingVertical: 8, paddingHorizontal: 10, marginTop: 10 }, deltaText: { fontSize: 11, fontWeight: "800" } });
