import { useMemo, useState } from "react";
import { Alert, Platform, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { buildLocalWorkoutHistoryRows } from "@/lib/local-workout-history";
import { buildMonthlyReportData, buildMonthlyReportHtml, getMonthKey } from "@/lib/monthly-report";
import { useWorkoutStore } from "@/lib/workout-store";

export default function ReportScreen() {
  const colors = useColors();
  const { completed, oneRmFormula } = useWorkoutStore();
  const rows = useMemo(() => buildLocalWorkoutHistoryRows(completed, oneRmFormula), [completed, oneRmFormula]);
  const months = useMemo(() => Array.from(new Set(rows.map((row) => getMonthKey(row.date)))).sort().reverse(), [rows]);
  const [selectedMonth, setSelectedMonth] = useState(new Date().toISOString().slice(0, 7));
  const month = months.includes(selectedMonth) ? selectedMonth : months[0] ?? selectedMonth;
  const report = buildMonthlyReportData(rows, month);
  const sharePdf = async () => { if (!report.rows.length) { Alert.alert("Нет данных", "Выбери месяц, в котором есть сохранённые тренировки."); return; } const html = buildMonthlyReportHtml(rows, month); try { if (Platform.OS === "web") { const popup = window.open("", "_blank"); if (!popup) throw new Error("Popup blocked"); popup.document.write(html); popup.document.close(); popup.focus(); popup.print(); return; } const { uri } = await Print.printToFileAsync({ html }); if (!(await Sharing.isAvailableAsync())) { Alert.alert("PDF создан", uri); return; } await Sharing.shareAsync(uri, { dialogTitle: `Итоги тренировок за ${month}`, mimeType: "application/pdf" }); } catch { Alert.alert("Не удалось сформировать PDF", "Не удалось создать файл. Проверь свободное место на устройстве."); } };
  return <ScreenContainer edges={["top", "left", "right", "bottom"]} className="px-5" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={() => router.back()}><IconSymbol name="chevron.left" size={27} color={colors.foreground} /></Pressable><Text style={[styles.headerTitle, { color: colors.foreground }]}>Месячный отчёт</Text><View style={{ width: 27 }} /></View><Text style={[styles.eyebrow, { color: colors.primary }]}>PDF-ИТОГИ</Text><Text style={[styles.title, { color: colors.foreground }]}>Выбери месяц</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.months}>{(months.length ? months : [month]).map((item) => <Pressable key={item} onPress={() => setSelectedMonth(item)} style={[styles.month, { backgroundColor: item === month ? colors.primary : colors.surface }]}><Text style={{ color: item === month ? "#101412" : colors.foreground, fontWeight: "800" }}>{item}</Text></Pressable>)}</ScrollView><View style={[styles.preview, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.previewTitle, { color: colors.foreground }]}>Предпросмотр отчёта</Text><View style={styles.metrics}><Metric value={String(report.trainingDays)} label="тренировок" colors={colors} /><Metric value={`${(report.totalVolumeKg / 1000).toFixed(1)} т`} label="объём" colors={colors} /><Metric value={`${report.bestOneRmKg.toFixed(1)} кг`} label="лучший 1RM" colors={colors} /></View><Text style={[styles.previewNote, { color: colors.muted }]}>В PDF войдут сводные показатели и таблица локально сохранённых подходов за выбранный месяц.</Text></View><Pressable onPress={sharePdf} style={[styles.export, { backgroundColor: colors.primary }]}><Text style={styles.exportText}>Сформировать PDF</Text><IconSymbol name="chevron.right" size={20} color="#101412" /></Pressable><Text style={[styles.note, { color: colors.muted }]}>На Android откроется системное меню сохранения или передачи PDF. В web-превью — диалог печати, где можно выбрать «Сохранить как PDF».</Text></ScrollView></ScreenContainer>;
}

function Metric({ value, label, colors }: { value: string; label: string; colors: { foreground: string; muted: string } }) { return <View style={styles.metric}><Text style={[styles.metricValue, { color: colors.foreground }]}>{value}</Text><Text style={[styles.metricLabel, { color: colors.muted }]}>{label}</Text></View>; }
const styles = StyleSheet.create({ content: { paddingTop: 16, paddingBottom: 34, gap: 14 }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, headerTitle: { fontSize: 16, fontWeight: "800" }, eyebrow: { fontSize: 10, fontWeight: "900", letterSpacing: 1.1, marginTop: 14 }, title: { fontSize: 26, fontWeight: "800", marginTop: 4 }, months: { gap: 8, paddingVertical: 4 }, month: { paddingHorizontal: 15, minHeight: 43, borderRadius: 13, justifyContent: "center" }, preview: { borderRadius: 18, borderWidth: 1, padding: 15 }, previewTitle: { fontSize: 16, fontWeight: "800" }, metrics: { flexDirection: "row", gap: 8, marginTop: 15 }, metric: { flex: 1 }, metricValue: { fontSize: 18, fontWeight: "900" }, metricLabel: { fontSize: 10, marginTop: 4 }, previewNote: { fontSize: 12, lineHeight: 18, marginTop: 17 }, export: { minHeight: 55, borderRadius: 16, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 }, exportText: { color: "#101412", fontWeight: "900", fontSize: 15 }, note: { fontSize: 12, lineHeight: 18 } });
