import { useMemo, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import Svg, { Circle, Line, Path, Polyline, Text as SvgText } from "react-native-svg";

import { BODY_METRICS, type BodyMeasurement, type BodyMetricId, type BodyProfile } from "@/lib/body-store";

export function BodyMetricChart({ measurements, colors }: { measurements: BodyMeasurement[]; colors: any }) {
  const [metricId, setMetricId] = useState<BodyMetricId>("weightKg");
  const metric = BODY_METRICS.find((item) => item.id === metricId) ?? BODY_METRICS[0];
  const points = useMemo(() => measurements.filter((item) => typeof item[metricId] === "number").slice().sort((a, b) => a.date.localeCompare(b.date)), [measurements, metricId]);
  const values = points.map((item) => item[metricId] as number); const min = Math.min(...values, 0); const max = Math.max(...values, 1); const span = Math.max(1, max - min); const width = 318; const height = 148; const left = 26; const right = 11; const top = 18; const bottom = 28;
  const chartPoints = points.map((item, index) => { const x = points.length === 1 ? width / 2 : left + ((width - left - right) * index) / (points.length - 1); const y = top + (height - top - bottom) * (1 - (((item[metricId] as number) - min) / span)); return { x, y, label: item.date.slice(5).replace("-", "."), value: item[metricId] as number }; });
  return <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.head}><View><Text style={[styles.kicker, { color: colors.primary }]}>ДИНАМИКА</Text><Text style={[styles.title, { color: colors.foreground }]}>{metric.label} · {metric.unit}</Text></View>{values.length ? <Text style={[styles.delta, { color: values.at(-1)! >= values[0] ? colors.primary : colors.success }]}>{values.length > 1 ? `${values.at(-1)! - values[0] >= 0 ? "+" : ""}${(values.at(-1)! - values[0]).toFixed(1)} ${metric.unit}` : "1 ЗАМЕР"}</Text> : null}</View><View style={styles.metricTabs}>{BODY_METRICS.map((item) => <Pressable key={item.id} onPress={() => setMetricId(item.id)} style={({ pressed }) => [styles.metricTab, { borderColor: item.id === metricId ? colors.primary : colors.border, backgroundColor: item.id === metricId ? colors.primary : colors.background, opacity: pressed ? 0.7 : 1 }]}><Text style={[styles.metricTabText, { color: item.id === metricId ? colors.surface : colors.foreground }]}>{item.short}</Text></Pressable>)}</View>{chartPoints.length >= 2 ? <><Svg width="100%" height={height} viewBox={`0 0 ${width} ${height}`}><Line x1={left} x2={width - right} y1={height - bottom} y2={height - bottom} stroke={colors.border} strokeWidth="1" /><Line x1={left} x2={left} y1={top} y2={height - bottom} stroke={colors.border} strokeWidth="1" /><Polyline points={chartPoints.map((point) => `${point.x},${point.y}`).join(" ")} fill="none" stroke={colors.primary} strokeWidth="3" />{chartPoints.map((point) => <Circle key={point.x} cx={point.x} cy={point.y} r="4.5" fill={colors.surface} stroke={colors.primary} strokeWidth="2.5" />)}{chartPoints.map((point) => <TextSvg key={`value-${point.x}`} x={point.x} y={point.y - 9} value={String(point.value)} color={colors.foreground} />)}</Svg><View style={styles.axis}>{chartPoints.map((point) => <Text key={point.x} style={[styles.axisText, { color: colors.muted }]}>{point.label}</Text>)}</View></> : <View style={styles.chartEmpty}><Text style={[styles.empty, { color: colors.muted }]}>Добавьте ещё один замер «{metric.label}», чтобы увидеть линию изменения.</Text></View>}</View>;
}

function TextSvg({ x, y, value, color }: { x: number; y: number; value: string; color: string }) { return <SvgText x={x} y={y} fill={color} textAnchor="middle" fontSize="9" fontWeight="900">{value}</SvgText>; }

export function BodySilhouette({ latest, profile, colors }: { latest?: BodyMeasurement; profile: BodyProfile; colors: any }) {
  const labels = BODY_METRICS.filter((metric) => ["chestCm", "waistCm", "hipsCm", "upperArmCm", "thighCm"].includes(metric.id) && latest?.[metric.id] !== undefined);
  const isFemale = profile === "female";
  const outline = isFemale ? "M51 49 C48 60 47 77 49 102 L52 145 C50 159 45 170 47 185 L53 231 M85 49 C88 60 89 77 87 102 L84 145 C86 159 91 170 89 185 L83 231 M51 52 C57 58 79 58 85 52 M49 72 L29 120 M87 72 L107 120 M29 120 L23 169 M107 120 L113 169 M52 145 C56 151 80 151 84 145 M47 185 C56 197 80 197 89 185 M53 231 L45 246 M83 231 L91 246" : "M50 49 C45 60 42 78 43 106 L48 161 L56 170 L53 232 M86 49 C91 60 94 78 93 106 L88 161 L80 170 L83 232 M50 52 C58 59 78 59 86 52 M44 71 L20 123 M92 71 L116 123 M20 123 L14 173 M116 123 L122 173 M48 161 C57 170 79 170 88 161 M54 232 L45 246 M82 232 L91 246";
  return <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.kicker, { color: colors.primary }]}>КАРТА ЗАМЕРОВ · {isFemale ? "ЖЕНСКИЙ ПРОФИЛЬ" : "МУЖСКОЙ ПРОФИЛЬ"}</Text><Text style={[styles.title, { color: colors.foreground }]}>Силуэт тела</Text>{latest ? <View style={styles.silhouetteRow}><Svg width="136" height="250" viewBox="0 0 136 250"><Circle cx="68" cy="26" r="19" fill="none" stroke={colors.foreground} strokeWidth="2" /><Path d={outline} fill="none" stroke={colors.foreground} strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round" /><Line x1={isFemale ? "43" : "39"} x2={isFemale ? "93" : "97"} y1="78" y2="78" stroke={colors.primary} strokeWidth="2" strokeDasharray="4 3" /><Line x1={isFemale ? "47" : "44"} x2={isFemale ? "89" : "92"} y1="112" y2="112" stroke={colors.primary} strokeWidth="2" strokeDasharray="4 3" /><Line x1={isFemale ? "44" : "47"} x2={isFemale ? "92" : "89"} y1="151" y2="151" stroke={colors.primary} strokeWidth="2" strokeDasharray="4 3" /></Svg><View style={styles.silhouetteValues}>{labels.map((metric) => <View key={metric.id} style={[styles.silhouetteMetric, { borderBottomColor: colors.border }]}><Text style={[styles.silhouetteLabel, { color: colors.muted }]}>{metric.label.toUpperCase()}</Text><Text style={[styles.silhouetteValue, { color: colors.foreground }]}>{latest[metric.id]} {metric.unit}</Text></View>)}</View></View> : <View style={styles.chartEmpty}><Text style={[styles.empty, { color: colors.muted }]}>Силуэт покажет актуальные обхваты после первого сохранённого замера.</Text></View>}</View>;
}

const styles = StyleSheet.create({ card: { margin: 12, borderWidth: 1, padding: 14, gap: 8 }, head: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-end" }, kicker: { fontSize: 9, fontWeight: "900", letterSpacing: .8 }, title: { fontSize: 18, fontWeight: "900", letterSpacing: -.5, marginTop: 2 }, delta: { fontSize: 12, fontWeight: "900" }, metricTabs: { flexDirection: "row", flexWrap: "wrap", gap: 5, marginTop: 4 }, metricTab: { minHeight: 28, paddingHorizontal: 7, justifyContent: "center", borderWidth: 1 }, metricTabText: { fontSize: 8, fontWeight: "900" }, axis: { flexDirection: "row", justifyContent: "space-between", marginTop: -20, paddingHorizontal: 25, gap: 2 }, axisText: { flex: 1, textAlign: "center", fontSize: 8, fontWeight: "800" }, chartEmpty: { minHeight: 132, alignItems: "center", justifyContent: "center", paddingHorizontal: 12 }, empty: { textAlign: "center", fontSize: 11, lineHeight: 16, fontWeight: "700" }, silhouetteRow: { flexDirection: "row", alignItems: "center", minHeight: 250 }, silhouetteValues: { flex: 1, gap: 2 }, silhouetteMetric: { paddingVertical: 9, borderBottomWidth: StyleSheet.hairlineWidth }, silhouetteLabel: { fontSize: 9, fontWeight: "900", letterSpacing: .6 }, silhouetteValue: { fontSize: 17, fontWeight: "900", marginTop: 2 } });
