import { useMemo, useState } from "react";
import { Image, Pressable, StyleSheet, Text, View } from "react-native";
import Svg, { Circle, Line, Polyline, Text as SvgText } from "react-native-svg";

import { BODY_METRICS, type BodyGoals, type BodyMeasurement, type BodyMetricId, type BodyProfile } from "@/lib/body-store";

export function BodyMetricChart({ measurements, goals, colors }: { measurements: BodyMeasurement[]; goals: BodyGoals; colors: any }) {
  const [metricId, setMetricId] = useState<BodyMetricId>("weightKg");
  const metric = BODY_METRICS.find((item) => item.id === metricId) ?? BODY_METRICS[0];
  const points = useMemo(() => measurements.filter((item) => typeof item[metricId] === "number").slice().sort((a, b) => a.date.localeCompare(b.date)), [measurements, metricId]);
  const values = points.map((item) => item[metricId] as number); const goal = goals[metricId]; const scaleValues = goal === undefined ? values : [...values, goal]; const min = Math.min(...scaleValues, 0); const max = Math.max(...scaleValues, 1); const span = Math.max(1, max - min); const width = 318; const height = 148; const left = 26; const right = 11; const top = 18; const bottom = 28; const goalY = goal === undefined ? undefined : top + (height - top - bottom) * (1 - ((goal - min) / span));
  const chartPoints = points.map((item, index) => { const x = points.length === 1 ? width / 2 : left + ((width - left - right) * index) / (points.length - 1); const y = top + (height - top - bottom) * (1 - (((item[metricId] as number) - min) / span)); return { x, y, label: item.date.slice(5).replace("-", "."), value: item[metricId] as number }; });
  return <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.head}><View><Text style={[styles.kicker, { color: colors.primary }]}>ДИНАМИКА</Text><Text style={[styles.title, { color: colors.foreground }]}>{metric.label} · {metric.unit}</Text></View>{values.length ? <Text style={[styles.delta, { color: values.at(-1)! >= values[0] ? colors.primary : colors.success }]}>{values.length > 1 ? `${values.at(-1)! - values[0] >= 0 ? "+" : ""}${(values.at(-1)! - values[0]).toFixed(1)} ${metric.unit}` : "1 ЗАМЕР"}</Text> : null}</View><View style={styles.metricTabs}>{BODY_METRICS.map((item) => <Pressable key={item.id} onPress={() => setMetricId(item.id)} style={({ pressed }) => [styles.metricTab, { borderColor: item.id === metricId ? colors.primary : colors.border, backgroundColor: item.id === metricId ? colors.primary : colors.background, opacity: pressed ? 0.7 : 1 }]}><Text style={[styles.metricTabText, { color: item.id === metricId ? colors.surface : colors.foreground }]}>{item.short}</Text></Pressable>)}</View>{goal !== undefined && <Text style={[styles.goalCaption, { color: colors.muted }]}>ЦЕЛЬ · {goal} {metric.unit}</Text>}{chartPoints.length >= 2 ? <><Svg width="100%" height={height} viewBox={`0 0 ${width} ${height}`}><Line x1={left} x2={width - right} y1={height - bottom} y2={height - bottom} stroke={colors.border} strokeWidth="1" /><Line x1={left} x2={left} y1={top} y2={height - bottom} stroke={colors.border} strokeWidth="1" />{goalY !== undefined && <Line x1={left} x2={width - right} y1={goalY} y2={goalY} stroke={colors.success} strokeWidth="2" strokeDasharray="5 4" />}<Polyline points={chartPoints.map((point) => `${point.x},${point.y}`).join(" ")} fill="none" stroke={colors.primary} strokeWidth="3" />{chartPoints.map((point) => <Circle key={point.x} cx={point.x} cy={point.y} r="4.5" fill={colors.surface} stroke={colors.primary} strokeWidth="2.5" />)}{chartPoints.map((point) => <TextSvg key={`value-${point.x}`} x={point.x} y={point.y - 9} value={String(point.value)} color={colors.foreground} />)}</Svg><View style={styles.axis}>{chartPoints.map((point) => <Text key={point.x} style={[styles.axisText, { color: colors.muted }]}>{point.label}</Text>)}</View></> : <View style={styles.chartEmpty}><Text style={[styles.empty, { color: colors.muted }]}>Добавьте ещё один замер «{metric.label}», чтобы увидеть линию изменения.</Text></View>}</View>;
}

function TextSvg({ x, y, value, color }: { x: number; y: number; value: string; color: string }) { return <SvgText x={x} y={y} fill={color} textAnchor="middle" fontSize="9" fontWeight="900">{value}</SvgText>; }

export function BodySilhouette({ latest, profile, colors }: { latest?: BodyMeasurement; profile: BodyProfile; colors: any }) {
  const labels = BODY_METRICS.filter((metric) => ["chestCm", "waistCm", "hipsCm", "upperArmCm", "thighCm"].includes(metric.id) && latest?.[metric.id] !== undefined);
  const isFemale = profile === "female";
  const silhouetteSource = isFemale ? require("../assets/images/body-silhouette-female.png") : require("../assets/images/body-silhouette-male.png");
  return <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.kicker, { color: colors.primary }]}>КАРТА ЗАМЕРОВ · {isFemale ? "ЖЕНСКИЙ ПРОФИЛЬ" : "МУЖСКОЙ ПРОФИЛЬ"}</Text><Text style={[styles.title, { color: colors.foreground }]}>Силуэт тела</Text>{latest ? <View style={styles.silhouetteRow}><View style={styles.silhouetteArt}><Image source={silhouetteSource} resizeMode="contain" style={styles.silhouetteImage} accessibilityLabel={isFemale ? "Реалистичный женский силуэт тела" : "Реалистичный мужской силуэт тела"} /><Svg width="146" height="250" viewBox="0 0 146 250" style={styles.measurementOverlay}><Line x1={isFemale ? "35" : "31"} x2={isFemale ? "111" : "115"} y1="84" y2="84" stroke={colors.primary} strokeWidth="2" strokeDasharray="5 3" /><Line x1={isFemale ? "44" : "40"} x2={isFemale ? "102" : "106"} y1="119" y2="119" stroke={colors.primary} strokeWidth="2" strokeDasharray="5 3" /><Line x1={isFemale ? "35" : "40"} x2={isFemale ? "111" : "106"} y1="151" y2="151" stroke={colors.primary} strokeWidth="2" strokeDasharray="5 3" /></Svg></View><View style={styles.silhouetteValues}>{labels.map((metric) => <View key={metric.id} style={[styles.silhouetteMetric, { borderBottomColor: colors.border }]}><Text style={[styles.silhouetteLabel, { color: colors.muted }]}>{metric.label.toUpperCase()}</Text><Text style={[styles.silhouetteValue, { color: colors.foreground }]}>{latest[metric.id]} {metric.unit}</Text></View>)}</View></View> : <View style={styles.chartEmpty}><Text style={[styles.empty, { color: colors.muted }]}>Силуэт покажет актуальные обхваты после первого сохранённого замера.</Text></View>}</View>;
}

const styles = StyleSheet.create({ card: { margin: 12, borderWidth: 1, padding: 14, gap: 8 }, head: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-end" }, kicker: { fontSize: 9, fontWeight: "900", letterSpacing: .8 }, title: { fontSize: 18, fontWeight: "900", letterSpacing: -.5, marginTop: 2 }, delta: { fontSize: 12, fontWeight: "900" }, metricTabs: { flexDirection: "row", flexWrap: "wrap", gap: 5, marginTop: 4 }, metricTab: { minHeight: 28, paddingHorizontal: 7, justifyContent: "center", borderWidth: 1 }, metricTabText: { fontSize: 8, fontWeight: "900" }, goalCaption: { fontSize: 9, fontWeight: "900", letterSpacing: .5 }, axis: { flexDirection: "row", justifyContent: "space-between", marginTop: -20, paddingHorizontal: 25, gap: 2 }, axisText: { flex: 1, textAlign: "center", fontSize: 8, fontWeight: "800" }, chartEmpty: { minHeight: 132, alignItems: "center", justifyContent: "center", paddingHorizontal: 12 }, empty: { textAlign: "center", fontSize: 11, lineHeight: 16, fontWeight: "700" }, silhouetteRow: { flexDirection: "row", alignItems: "center", minHeight: 250 }, silhouetteArt: { width: 146, height: 250, position: "relative" }, silhouetteImage: { width: 146, height: 250 }, measurementOverlay: { position: "absolute", left: 0, top: 0 }, silhouetteValues: { flex: 1, gap: 2 }, silhouetteMetric: { paddingVertical: 9, borderBottomWidth: StyleSheet.hairlineWidth }, silhouetteLabel: { fontSize: 9, fontWeight: "900", letterSpacing: .6 }, silhouetteValue: { fontSize: 17, fontWeight: "900", marginTop: 2 } });
