import { useEffect, useMemo, useState } from "react";
import { Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useColors } from "@/hooks/use-colors";
import { exercises, getExercise } from "@/lib/workout-data";
import { openReplacementPicker, selectReplacementExercise, subscribeToReplacementPicker } from "@/lib/exercise-replacement-bus";

export function WorkoutReplacementOverlay() {
  const colors = useColors();
  const [originalId, setOriginalId] = useState<string | null>(null);
  const [query, setQuery] = useState("");
  const current = getExercise(originalId ?? "");
  const options = useMemo(() => exercises.filter((exercise) => exercise.id !== originalId && `${exercise.name} ${exercise.group} ${exercise.equipment}`.toLowerCase().includes(query.trim().toLowerCase())), [originalId, query]);
  useEffect(() => subscribeToReplacementPicker((id) => { setOriginalId(id); setQuery(""); }), []);
  const close = () => { setOriginalId(null); setQuery(""); };
  const choose = (replacementId: string) => { if (originalId) selectReplacementExercise({ originalId, replacementId }); close(); };
  return <Modal visible={Boolean(originalId)} transparent animationType="slide" onRequestClose={close}><View style={styles.backdrop}><View style={[styles.sheet, { backgroundColor: colors.background }]}><View style={styles.header}><View style={{ flex: 1 }}><Text style={[styles.title, { color: colors.foreground }]}>Заменить упражнение</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Вместо «{current?.name ?? "упражнение"}»</Text></View><Pressable onPress={close} style={[styles.close, { backgroundColor: colors.surface }]}><Text style={[styles.closeText, { color: colors.foreground }]}>×</Text></Pressable></View><View style={[styles.search, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={{ color: colors.muted, fontSize: 18 }}>⌕</Text><TextInput value={query} onChangeText={setQuery} placeholder="Поиск: название, группа, оборудование" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.foreground }]} autoFocus /></View><Text style={[styles.counter, { color: colors.primary }]}>{options.length} упражнений</Text><ScrollView contentContainerStyle={styles.list} keyboardShouldPersistTaps="handled">{options.map((exercise) => <Pressable key={exercise.id} onPress={() => choose(exercise.id)} style={({ pressed }) => [styles.option, { backgroundColor: colors.surface, borderColor: colors.border }, pressed && { opacity: 0.72 }]}><View style={[styles.badge, { backgroundColor: colors.primary + "20" }]}><Text style={[styles.badgeText, { color: colors.primary }]}>{exercise.group.slice(0, 1)}</Text></View><View style={{ flex: 1 }}><Text style={[styles.name, { color: colors.foreground }]}>{exercise.name}</Text><Text style={[styles.meta, { color: colors.muted }]}>{exercise.group} · {exercise.equipment}</Text></View><Text style={[styles.choose, { color: colors.primary }]}>Выбрать</Text></Pressable>)}{!options.length && <Text style={[styles.empty, { color: colors.muted }]}>Ничего не найдено. Попробуйте другой запрос.</Text>}</ScrollView></View></View></Modal>;
}

const styles = StyleSheet.create({ backdrop: { flex: 1, backgroundColor: "#090611B8", justifyContent: "flex-end" }, sheet: { maxHeight: "88%", borderTopLeftRadius: 28, borderTopRightRadius: 28, padding: 20, gap: 12 }, header: { flexDirection: "row", gap: 12, alignItems: "flex-start" }, title: { fontSize: 21, fontWeight: "900" }, subtitle: { fontSize: 12, marginTop: 4 }, close: { width: 36, height: 36, borderRadius: 18, alignItems: "center", justifyContent: "center" }, closeText: { fontSize: 24, lineHeight: 26 }, search: { height: 48, borderRadius: 14, borderWidth: 1, flexDirection: "row", alignItems: "center", gap: 8, paddingHorizontal: 12 }, input: { flex: 1, fontSize: 13 }, counter: { fontSize: 11, fontWeight: "900" }, list: { gap: 8, paddingBottom: 12 }, option: { minHeight: 67, borderRadius: 15, borderWidth: 1, padding: 11, flexDirection: "row", alignItems: "center", gap: 10 }, badge: { width: 34, height: 34, borderRadius: 11, justifyContent: "center", alignItems: "center" }, badgeText: { fontSize: 15, fontWeight: "900" }, name: { fontSize: 13, fontWeight: "900" }, meta: { fontSize: 10, marginTop: 4 }, choose: { fontSize: 11, fontWeight: "900" }, empty: { textAlign: "center", paddingVertical: 30, fontSize: 13 } });
