import AsyncStorage from "@react-native-async-storage/async-storage";
import { createContext, useContext, useEffect, useMemo, useState } from "react";
import type { FoodEntry, FoodProduct } from "./nutrition-data";
import { nutritionEntryFingerprint } from "./nutrition-import";

type NutritionStore = { entries: FoodEntry[]; dailyCalorieGoal: number; snackPosition: 0 | 1; favoriteProductIds: string[]; customProducts: FoodProduct[]; ready: boolean; addEntry: (input: Omit<FoodEntry, "id">) => void; importEntries: (inputs: Omit<FoodEntry, "id">[]) => number; removeEntry: (id: string) => void; setDailyCalorieGoal: (goal: number) => void; setSnackPosition: (position: 0 | 1) => void; toggleFavoriteProduct: (productId: string) => void; addCustomProduct: (input: Omit<FoodProduct, "id">) => FoodProduct };
const Context = createContext<NutritionStore | null>(null);
const KEY = "ironrise.nutrition.v1";

export function NutritionProvider({ children }: { children: React.ReactNode }) {
  const [entries, setEntries] = useState<FoodEntry[]>([]); const [dailyCalorieGoal, setDailyCalorieGoal] = useState(2200); const [snackPosition, setSnackPosition] = useState<0 | 1>(0); const [favoriteProductIds, setFavoriteProductIds] = useState<string[]>([]); const [customProducts, setCustomProducts] = useState<FoodProduct[]>([]); const [ready, setReady] = useState(false);
  useEffect(() => { AsyncStorage.getItem(KEY).then((raw) => { if (!raw) return; const parsed = JSON.parse(raw) as FoodEntry[] | { entries?: FoodEntry[]; dailyCalorieGoal?: number; snackPosition?: number; favoriteProductIds?: string[]; customProducts?: FoodProduct[] }; if (Array.isArray(parsed)) setEntries(parsed); else { setEntries(parsed.entries ?? []); if (Number.isFinite(parsed.dailyCalorieGoal) && (parsed.dailyCalorieGoal ?? 0) > 0) setDailyCalorieGoal(parsed.dailyCalorieGoal!); if (parsed.snackPosition === 1) setSnackPosition(1); if (Array.isArray(parsed.favoriteProductIds)) setFavoriteProductIds(parsed.favoriteProductIds.filter((id): id is string => typeof id === "string")); if (Array.isArray(parsed.customProducts)) setCustomProducts(parsed.customProducts.filter((product): product is FoodProduct => typeof product?.id === "string" && typeof product.name === "string" && Number.isFinite(product.kcalPer100g) && Number.isFinite(product.proteinPer100g) && Number.isFinite(product.fatPer100g) && Number.isFinite(product.carbsPer100g))); } }).catch(() => undefined).finally(() => setReady(true)); }, []);
  useEffect(() => { if (ready) void AsyncStorage.setItem(KEY, JSON.stringify({ entries, dailyCalorieGoal, snackPosition, favoriteProductIds, customProducts })); }, [entries, dailyCalorieGoal, snackPosition, favoriteProductIds, customProducts, ready]);
  const value = useMemo(() => ({ entries, dailyCalorieGoal, snackPosition, favoriteProductIds, customProducts, ready, addEntry: (input: Omit<FoodEntry, "id">) => setEntries((current) => [{ ...input, id: `food-${Date.now()}` }, ...current]), importEntries: (inputs: Omit<FoodEntry, "id">[]) => { const existing = new Set(entries.map(nutritionEntryFingerprint)); const accepted = inputs.filter((entry) => { const key = nutritionEntryFingerprint(entry); if (existing.has(key)) return false; existing.add(key); return true; }); if (accepted.length) setEntries((current) => [...accepted.map((entry, index) => ({ ...entry, id: `import-${Date.now()}-${index}` })), ...current]); return accepted.length; }, removeEntry: (id: string) => setEntries((current) => current.filter((entry) => entry.id !== id)), setDailyCalorieGoal: (goal: number) => setDailyCalorieGoal(Math.max(1, Math.round(goal))), setSnackPosition, toggleFavoriteProduct: (productId: string) => setFavoriteProductIds((current) => current.includes(productId) ? current.filter((id) => id !== productId) : [...current, productId]), addCustomProduct: (input: Omit<FoodProduct, "id">) => { const product = { ...input, id: `custom-food-${Date.now()}` }; setCustomProducts((current) => [product, ...current]); return product; } }), [entries, dailyCalorieGoal, snackPosition, favoriteProductIds, customProducts, ready]);
  return <Context.Provider value={value}>{children}</Context.Provider>;
}
export function useNutritionStore() { const value = useContext(Context); if (!value) throw new Error("NutritionProvider missing"); return value; }
