import { useMemo, useState } from "react";
import { Alert, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { BODY_METRICS, type BodyMeasurement, useBodyStore } from "@/lib/body-store";
import { BodyMetricChart, BodySilhouette } from "@/components/body-visuals";

const localDate = () => { const now = new Date(); return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-${String(now.getDate()).padStart(2, "0")}`; };
const emptyDraft = () => Object.fromEntries(BODY_METRICS.map((metric) => [metric.id, ""])) as Record<typeof BODY_METRICS[number]["id"], string>;

export default function BodyScreen() {
  const colors = useColors();
  const { measurements, addMeasurement, removeMeasurement } = useBodyStore();
  const [editorOpen, setEditorOpen] = useState(false);
  const [date, setDate] = useState(localDate);
  const [draft, setDraft] = useState(emptyDraft);
  const latest = measurements[0];
  const measurementsCount = measurements.length;
  const save = () => { const values = BODY_METRICS.reduce<Partial<BodyMeasurement>>((next, metric) => { const value = Number(draft[metric.id].replace(",", ".")); return Number.isFinite(value) && value > 0 ? { ...next, [metric.id]: value } : next; }, {}); if (!Object.keys(values).length) { Alert.alert("Добавьте параметр", "Укажите хотя бы вес или один обхват."); return; } addMeasurement({ date, ...values }); setEditorOpen(false); setDate(localDate()); setDraft(emptyDraft()); };
  const formattedDate = useMemo(() => latest?.date ? new Date(`${latest.date}T12:00:00`).toLocaleDateString("ru-RU", { day: "numeric", month: "long" }) : "нет записей", [latest?.date]);
  return <ScreenContainer className="px-0" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={[styles.topLine, { backgroundColor: colors.primary }]} /><View style={[styles.header, { borderBottomColor: colors.border }]}><View><Text style={[styles.eyebrow, { color: colors.primary }]}>ЛОКАЛЬНЫЙ ЖУРНАЛ</Text><Text style={[styles.title, { color: colors.foreground }]}>ТЕЛО</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Вес, обхваты и композиция</Text></View><Pressable onPress={() => setEditorOpen(true)} style={({ pressed }) => [styles.addButton, { backgroundColor: colors.primary, opacity: pressed ? 0.7 : 1 }]}><Text style={styles.addButtonText}>+ ЗАМЕР</Text></Pressable></View>
    <View style={[styles.latest, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.latestKicker, { color: colors.primary }]}>ПОСЛЕДНИЙ ЗАМЕР · {formattedDate.toUpperCase()}</Text>{latest ? <View style={styles.latestGrid}>{BODY_METRICS.filter((metric) => latest[metric.id] !== undefined).slice(0, 4).map((metric) => <View key={metric.id} style={[styles.latestMetric, { borderColor: colors.border }]}><Text style={[styles.latestValue, { color: colors.foreground }]}>{latest[metric.id]}<Text style={styles.latestUnit}> {metric.unit}</Text></Text><Text style={[styles.latestLabel, { color: colors.muted }]}>{metric.short}</Text></View>)}</View> : <Text style={[styles.empty, { color: colors.muted }]}>Добавьте первый замер, чтобы видеть динамику тела.</Text>}</View>
    <BodyMetricChart measurements={measurements} colors={colors} />
    <BodySilhouette latest={latest} colors={colors} />
    <View style={styles.sectionHead}><Text style={[styles.sectionTitle, { color: colors.foreground }]}>ИСТОРИЯ</Text><Text style={[styles.sectionMeta, { color: colors.muted }]}>{measurementsCount} {measurementsCount === 1 ? "запись" : "записей"}</Text></View>
    {measurements.length ? measurements.map((measurement) => <MeasurementRow key={measurement.id} item={measurement} colors={colors} onDelete={() => Alert.alert("Удалить замер?", "Запись исчезнет только из локального журнала.", [{ text: "Отмена", style: "cancel" }, { text: "Удалить", style: "destructive", onPress: () => removeMeasurement(measurement.id) }])} />) : <View style={[styles.historyEmpty, { borderColor: colors.border }]}><Text style={[styles.empty, { color: colors.muted }]}>История пока пуста.</Text></View>}
  </ScrollView>
  <Modal visible={editorOpen} transparent animationType="slide" onRequestClose={() => setEditorOpen(false)}><View style={styles.backdrop}><View style={[styles.sheet, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.sheetHeader}><View><Text style={[styles.eyebrow, { color: colors.primary }]}>НОВАЯ ЗАПИСЬ</Text><Text style={[styles.sheetTitle, { color: colors.foreground }]}>Замеры тела</Text></View><Pressable onPress={() => setEditorOpen(false)} style={[styles.close, { borderColor: colors.border }]}><Text style={[styles.closeText, { color: colors.foreground }]}>×</Text></Pressable></View><Text style={[styles.inputLabel, { color: colors.muted }]}>Дата · ГГГГ-ММ-ДД</Text><TextInput value={date} onChangeText={setDate} placeholder="2026-08-19" placeholderTextColor={colors.muted} style={[styles.dateInput, { color: colors.foreground, borderColor: colors.border, backgroundColor: colors.background }]} />
    <View style={styles.fields}>{BODY_METRICS.map((metric) => <View key={metric.id} style={styles.field}><Text style={[styles.inputLabel, { color: colors.muted }]}>{metric.label}, {metric.unit}</Text><TextInput value={draft[metric.id]} onChangeText={(value) => setDraft((current) => ({ ...current, [metric.id]: value }))} keyboardType="decimal-pad" placeholder="—" placeholderTextColor={colors.muted} style={[styles.dateInput, { color: colors.foreground, borderColor: colors.border, backgroundColor: colors.background }]} /></View>)}</View><Pressable onPress={save} style={({ pressed }) => [styles.saveButton, { backgroundColor: colors.primary, opacity: pressed ? 0.7 : 1 }]}><Text style={styles.saveText}>СОХРАНИТЬ ЗАМЕР</Text></Pressable></View></View></Modal>
  </ScreenContainer>;
}

function MeasurementRow({ item, colors, onDelete }: { item: BodyMeasurement; colors: any; onDelete: () => void }) { return <View style={[styles.measurementRow, { borderColor: colors.border, backgroundColor: colors.surface }]}><View style={styles.measurementInfo}><Text style={[styles.measurementDate, { color: colors.foreground }]}>{new Date(`${item.date}T12:00:00`).toLocaleDateString("ru-RU", { day: "numeric", month: "short", year: "numeric" })}</Text><Text style={[styles.measurementValues, { color: colors.muted }]}>{BODY_METRICS.filter((metric) => item[metric.id] !== undefined).map((metric) => `${metric.short} ${item[metric.id]} ${metric.unit}`).join(" · ")}</Text></View><Pressable onPress={onDelete} style={({ pressed }) => [styles.delete, { borderColor: colors.border, opacity: pressed ? 0.65 : 1 }]}><Text style={[styles.deleteText, { color: colors.error }]}>×</Text></Pressable></View>; }

const styles = StyleSheet.create({ content: { paddingBottom: 28 }, topLine: { height: 8 }, header: { minHeight: 138, paddingHorizontal: 18, paddingVertical: 20, borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between", gap: 12 }, eyebrow: { fontSize: 10, fontWeight: "900", letterSpacing: 1.2 }, title: { fontSize: 48, fontWeight: "900", letterSpacing: -2, marginTop: 3 }, subtitle: { fontSize: 12, fontWeight: "700", marginTop: 4 }, addButton: { minHeight: 42, paddingHorizontal: 13, alignItems: "center", justifyContent: "center" }, addButtonText: { color: "#FFFDF8", fontSize: 10, fontWeight: "900", letterSpacing: .7 }, latest: { margin: 12, borderWidth: 1, padding: 14, gap: 12 }, latestKicker: { fontSize: 9, fontWeight: "900", letterSpacing: .8 }, latestGrid: { flexDirection: "row", flexWrap: "wrap" }, latestMetric: { width: "50%", minHeight: 66, borderTopWidth: StyleSheet.hairlineWidth, paddingTop: 8 }, latestValue: { fontSize: 25, fontWeight: "900", letterSpacing: -1 }, latestUnit: { fontSize: 10, letterSpacing: 0 }, latestLabel: { fontSize: 9, fontWeight: "900", marginTop: 3, letterSpacing: .6 }, empty: { fontSize: 12, lineHeight: 17, fontWeight: "700" }, sectionHead: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingHorizontal: 18, marginTop: 12, marginBottom: 7 }, sectionTitle: { fontSize: 15, fontWeight: "900", letterSpacing: .6 }, sectionMeta: { fontSize: 10, fontWeight: "800" }, historyEmpty: { marginHorizontal: 12, borderWidth: 1, padding: 16 }, measurementRow: { marginHorizontal: 12, marginTop: 8, minHeight: 76, borderWidth: 1, padding: 12, flexDirection: "row", gap: 10, alignItems: "center" }, measurementInfo: { flex: 1 }, measurementDate: { fontSize: 14, fontWeight: "900", textTransform: "uppercase" }, measurementValues: { fontSize: 10, lineHeight: 15, fontWeight: "700", marginTop: 6 }, delete: { width: 32, height: 32, alignItems: "center", justifyContent: "center", borderWidth: 1 }, deleteText: { fontSize: 22, lineHeight: 23 }, backdrop: { flex: 1, backgroundColor: "#090611B8", justifyContent: "flex-end" }, sheet: { borderTopWidth: 1, padding: 18, gap: 10 }, sheetHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 4 }, sheetTitle: { fontSize: 25, fontWeight: "900", letterSpacing: -1, marginTop: 2 }, close: { width: 36, height: 36, borderWidth: 1, alignItems: "center", justifyContent: "center" }, closeText: { fontSize: 25, lineHeight: 27 }, inputLabel: { fontSize: 9, fontWeight: "900", letterSpacing: .5 }, dateInput: { minHeight: 44, borderWidth: 1, paddingHorizontal: 11, marginTop: 5, fontSize: 15, fontWeight: "800" }, fields: { flexDirection: "row", flexWrap: "wrap", gap: 9 }, field: { width: "48%" }, saveButton: { minHeight: 52, alignItems: "center", justifyContent: "center", marginTop: 4 }, saveText: { color: "#FFFDF8", fontSize: 11, fontWeight: "900", letterSpacing: .7 } });
