import { useMemo, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import { Image } from "expo-image";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { exercises, muscleGroups, type MuscleGroup } from "@/lib/workout-data";

export default function ExercisesScreen() {
  const colors = useColors(); const [query, setQuery] = useState(""); const [active, setActive] = useState<MuscleGroup | "Все">("Все");
  const filtered = useMemo(() => exercises.filter((e) => (active === "Все" || e.group === active) && e.name.toLowerCase().includes(query.toLowerCase())), [active, query]);
  return <ScreenContainer className="px-5" containerClassName="bg-background"><FlatList data={filtered} keyExtractor={(item) => item.id} showsVerticalScrollIndicator={false} contentContainerStyle={styles.content} ListHeaderComponent={<View><Text style={[styles.eyebrow, { color: colors.primary }]}>БАЗА ДВИЖЕНИЙ</Text><Text style={[styles.title, { color: colors.foreground }]}>Упражнения</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Выбирай движение и добавляй его в свою программу</Text><View style={[styles.search, { backgroundColor: colors.surface }]}><Text style={{ color: colors.muted, fontSize: 18 }}>⌕</Text><TextInput value={query} onChangeText={setQuery} placeholder="Найти упражнение" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.foreground }]} /></View><FlatList horizontal data={muscleGroups} keyExtractor={(item) => item} showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters} renderItem={({ item }) => <Pressable onPress={() => setActive(item)} style={[styles.filter, { backgroundColor: active === item ? colors.primary : colors.surface }]}><Text style={{ color: active === item ? "#101412" : colors.muted, fontSize: 12, fontWeight: "800" }}>{item}</Text></Pressable>} /></View>} renderItem={({ item }) => <Pressable onPress={() => router.push({ pathname: "/exercise/[id]", params: { id: item.id } })} style={({ pressed }) => [styles.card, { backgroundColor: colors.surface, borderColor: colors.border }, pressed && { opacity: 0.75 }]}><Image source={item.image} contentFit="cover" transition={200} style={styles.image} /><View style={styles.cardBody}><View style={styles.cardTop}><Text style={[styles.cardTitle, { color: colors.foreground }]}>{item.name}</Text><Text style={[styles.group, { color: colors.primary }]}>{item.group}</Text></View><Text style={[styles.equipment, { color: colors.muted }]}>{item.equipment} · личный рекорд {item.recordKg ? `${item.recordKg} кг` : `${item.recordReps} сек`}</Text></View></Pressable>} ListEmptyComponent={<Text style={{ color: colors.muted, paddingVertical: 24 }}>Ничего не найдено. Попробуй другой запрос.</Text>} /></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingTop: 18, paddingBottom: 30, gap: 12 }, eyebrow: { fontSize: 11, fontWeight: "800", letterSpacing: 1.2 }, title: { fontSize: 30, fontWeight: "800", marginTop: 5 }, subtitle: { fontSize: 14, lineHeight: 20, marginTop: 7 }, search: { marginTop: 18, borderRadius: 15, paddingHorizontal: 14, flexDirection: "row", alignItems: "center", gap: 8, height: 48 }, input: { flex: 1, fontSize: 14 }, filters: { gap: 8, paddingVertical: 14 }, filter: { borderRadius: 13, paddingHorizontal: 13, paddingVertical: 9 }, card: { flexDirection: "row", borderRadius: 18, borderWidth: 1, overflow: "hidden", minHeight: 104 }, image: { width: 105, height: 104 }, cardBody: { flex: 1, padding: 13, justifyContent: "center" }, cardTop: { gap: 8 }, cardTitle: { fontSize: 15, fontWeight: "800", lineHeight: 19 }, group: { fontSize: 11, fontWeight: "800" }, equipment: { fontSize: 11, marginTop: 9 } });
