import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import Svg, { Line, Rect } from "react-native-svg";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { useWorkoutStore } from "@/lib/workout-store";
import { getProgram, formatDuration } from "@/lib/workout-data";
import { buildHomeWorkoutTrend, type HomeWorkoutTrendPoint } from "@/lib/home-workout-trend";

export default function HomeScreen() {
  const colors = useColors();
  const { programs, completed, scheduled, startWorkout } = useWorkoutStore();
  const today = new Date().toISOString().slice(0, 10);
  const todaySchedule = scheduled[today];
  const todayProgram = todaySchedule ? getProgram(todaySchedule.programId) ?? programs.find((program) => program.id === todaySchedule.programId) : undefined;
  const weekVolume = completed.reduce((sum, item) => sum + item.totalVolume, 0);
  const workoutTrend = buildHomeWorkoutTrend(completed);
  return <ScreenContainer className="px-5" containerClassName="bg-background">
    <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
      <View style={styles.topRow}><View><Text style={[styles.eyebrow, { color: colors.primary }]}>ЧЕТВЕРГ, 13 АВГУСТА</Text><Text style={[styles.title, { color: colors.foreground }]}>Готов к работе?</Text></View><Pressable onPress={() => router.push("/calendar")} style={({ pressed }) => [styles.iconButton, { backgroundColor: colors.surface }, pressed && { opacity: 0.7 }]}><IconSymbol name="calendar" size={22} color={colors.foreground} /></Pressable></View>
      <View style={[styles.heroCard, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.heroLedgerRule, { backgroundColor: colors.primary }]} /><View style={styles.heroTop}><Text style={[styles.heroLabel, { color: colors.primary }]}>ТРЕНИРОВКА ДНЯ</Text><Text style={[styles.heroBadge, { color: colors.foreground, backgroundColor: colors.background }]}>{todaySchedule?.time ?? "НЕТ ПЛАНА"}</Text></View>{todayProgram ? <><Text style={[styles.heroTitle, { color: colors.foreground }]}>{todayProgram.name}</Text><Text style={[styles.heroDescription, { color: colors.muted }]}>{todayProgram.description}</Text><View style={styles.heroMeta}><Text style={[styles.heroMetaText, { color: colors.muted }]}>{todayProgram.exercises.length} упражнений</Text><Text style={[styles.heroMetaText, { color: colors.muted }]}>≈ {todayProgram.exercises.reduce((sum, item) => sum + Math.ceil((item.sets * 45 + item.rest * (item.sets - 1)) / 60), 0)} мин</Text></View><Pressable onPress={() => { startWorkout(todayProgram.id); router.push({ pathname: "/workout", params: { programId: todayProgram.id } }); }} style={({ pressed }) => [styles.startButton, { backgroundColor: colors.foreground }, pressed && { transform: [{ scale: 0.97 }] }]}><Text style={[styles.startText, { color: colors.surface }]}>Начать тренировку</Text><IconSymbol name="arrow.forward" size={19} color={colors.surface} /></Pressable></> : <><Text style={[styles.heroTitle, { color: colors.foreground }]}>Тренировка на сегодня не запланирована</Text><Text style={[styles.heroDescription, { color: colors.muted }]}>Выберите программу в календаре, и она появится здесь.</Text><Pressable onPress={() => router.push("/(tabs)/calendar")} style={({ pressed }) => [styles.startButton, { backgroundColor: colors.foreground }, pressed && { transform: [{ scale: 0.97 }] }]}><Text style={[styles.startText, { color: colors.surface }]}>Запланировать тренировку</Text><IconSymbol name="calendar" size={19} color={colors.surface} /></Pressable></>}</View>
      <View style={styles.sectionHeader}><Text style={[styles.sectionTitle, { color: colors.foreground }]}>Эта неделя</Text><Text style={[styles.sectionLink, { color: colors.primary }]}>{completed.length} тренировки</Text></View>
      <View style={styles.statsRow}><Metric label="Тренировки" value={String(completed.length)} suffix="шт" colors={colors} /><Metric label="Общий объём" value={(weekVolume / 1000).toFixed(1)} suffix="т" colors={colors} /><Metric label="Время" value={formatDuration(completed.reduce((sum, item) => sum + item.durationMinutes, 0)).replace(" ч 0 мин", " ч")} suffix="" colors={colors} /></View>
      <CompletedWorkoutChart points={workoutTrend} colors={colors} />
      <View style={styles.sectionHeader}><Text style={[styles.sectionTitle, { color: colors.foreground }]}>Быстрый доступ</Text></View>
      <View style={styles.quickGrid}><QuickAction icon="dumbbell.fill" label="Каталог упражнений" onPress={() => router.push("/(tabs)/exercises")} colors={colors} /><QuickAction icon="calendar" label="Календарь" onPress={() => router.push("/(tabs)/calendar")} colors={colors} /></View>
      <View style={[styles.tipCard, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.tipIcon, { backgroundColor: "#FF9F4320" }]}><IconSymbol name="lightbulb" size={20} color="#FF9F43" /></View><View style={{ flex: 1 }}><Text style={[styles.tipTitle, { color: colors.foreground }]}>Совет дня</Text><Text style={[styles.tipText, { color: colors.muted }]}>Фиксируй фактический вес — так рекорды и прогресс будут точнее.</Text></View></View>
    </ScrollView>
  </ScreenContainer>;
}
function Metric({ label, value, suffix, colors }: { label: string; value: string; suffix: string; colors: any }) { return <Pressable onPress={() => router.push("/(tabs)/stats")} style={({ pressed }) => [styles.metric, { backgroundColor: colors.surface, borderColor: colors.border, borderLeftColor: colors.primary, opacity: pressed ? 0.72 : 1 }]}><Text style={[styles.metricValue, { color: colors.foreground }]}>{value}<Text style={{ fontSize: 13, color: colors.muted }}>{suffix}</Text></Text><Text style={[styles.metricLabel, { color: colors.muted }]}>{label}</Text></Pressable>; }
function CompletedWorkoutChart({ points, colors }: { points: HomeWorkoutTrendPoint[]; colors: any }) {
  const width = 310; const height = 126; const paddingX = 16; const baseline = 98;
  const maxVolume = Math.max(1, ...points.map((point) => point.volume));
  const barGap = 10; const barWidth = points.length ? Math.max(18, Math.min(34, (width - paddingX * 2 - barGap * Math.max(0, points.length - 1)) / points.length)) : 0;
  return <View style={[styles.chartCard, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.chartHeader}><View><Text style={[styles.chartTitle, { color: colors.foreground }]}>Завершённые тренировки</Text><Text style={[styles.chartHint, { color: colors.muted }]}>Нажмите столбец, чтобы открыть тренировку</Text></View><Pressable onPress={() => router.push("/(tabs)/stats")}><Text style={[styles.chartLink, { color: colors.primary }]}>Статистика</Text></Pressable></View>{points.length ? <><Svg width="100%" height={height} viewBox={`0 0 ${width} ${height}`}><Line x1={paddingX} x2={width - paddingX} y1={baseline} y2={baseline} stroke={colors.border} strokeWidth="1" />{points.map((point, index) => { const x = paddingX + index * (barWidth + barGap); const barHeight = Math.max(8, (point.volume / maxVolume) * 72); return <Rect key={point.date} x={x} y={baseline - barHeight} width={barWidth} height={barHeight} rx="6" fill={index === points.length - 1 ? colors.primary : `${colors.primary}55`} onPress={() => router.push({ pathname: "/workout-history/[id]", params: { id: point.workoutId } })} />; })}</Svg><View style={styles.chartAxis}>{points.map((point) => <Pressable key={point.date} onPress={() => router.push({ pathname: "/workout-history/[id]", params: { id: point.workoutId } })} style={styles.chartAxisPress}><Text style={[styles.chartAxisLabel, { color: colors.muted }]}>{point.label}</Text></Pressable>)}</View></> : <Text style={[styles.chartEmpty, { color: colors.muted }]}>Заверши первую тренировку — здесь появится её динамика.</Text>}</View>;
}
function QuickAction({ icon, label, onPress, colors }: { icon: any; label: string; onPress: () => void; colors: any }) { return <Pressable onPress={onPress} style={({ pressed }) => [styles.quick, { backgroundColor: colors.surface, borderColor: colors.border }, pressed && { opacity: 0.7 }]}><IconSymbol name={icon} size={22} color={colors.primary} /><Text style={[styles.quickText, { color: colors.foreground }]}>{label}</Text><IconSymbol name="chevron.right" size={18} color={colors.muted} /></Pressable>; }
const styles = StyleSheet.create({ content: { paddingTop: 18, paddingBottom: 34, gap: 18 }, topRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, eyebrow: { fontSize: 11, fontWeight: "800", letterSpacing: 1.2 }, title: { fontSize: 30, fontWeight: "800", marginTop: 5, letterSpacing: -0.6 }, iconButton: { width: 42, height: 42, borderRadius: 6, alignItems: "center", justifyContent: "center" }, heroCard: { borderRadius: 8, borderWidth: 1, padding: 20, paddingLeft: 25, marginTop: 8, position: "relative", overflow: "hidden" }, heroLedgerRule: { position: "absolute", left: 0, top: 0, bottom: 0, width: 7 }, heroTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, heroLabel: { fontSize: 11, fontWeight: "900", letterSpacing: 1 }, heroBadge: { fontSize: 10, fontWeight: "800", paddingHorizontal: 9, paddingVertical: 5, borderRadius: 3 }, heroTitle: { fontSize: 24, fontWeight: "800", marginTop: 22 }, heroDescription: { fontSize: 14, marginTop: 7, lineHeight: 20 }, heroMeta: { flexDirection: "row", gap: 18, marginTop: 17 }, heroMetaText: { fontWeight: "700", fontSize: 13 }, startButton: { borderRadius: 5, paddingVertical: 14, paddingHorizontal: 16, marginTop: 20, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, startText: { fontSize: 15, fontWeight: "800" }, sectionHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 4 }, sectionTitle: { fontSize: 19, fontWeight: "800" }, sectionLink: { fontSize: 13, fontWeight: "700" }, statsRow: { flexDirection: "row", gap: 9 }, metric: { flex: 1, padding: 13, borderWidth: 1, borderLeftWidth: 4, borderRadius: 5 }, metricValue: { fontSize: 21, fontWeight: "800" }, metricLabel: { fontSize: 11, marginTop: 6 }, chartCard: { borderWidth: 1, borderRadius: 6, padding: 14, marginTop: -2 }, chartHeader: { flexDirection: "row", justifyContent: "space-between", gap: 10, alignItems: "flex-start" }, chartTitle: { fontSize: 14, fontWeight: "900" }, chartHint: { fontSize: 10, marginTop: 3 }, chartLink: { fontSize: 11, fontWeight: "900", paddingVertical: 3 }, chartAxis: { flexDirection: "row", justifyContent: "space-between", gap: 4 }, chartAxisPress: { flex: 1, alignItems: "center" }, chartAxisLabel: { fontSize: 9, maxWidth: 42, textAlign: "center" }, chartEmpty: { height: 100, textAlign: "center", textAlignVertical: "center", fontSize: 12, lineHeight: 18 }, quickGrid: { gap: 9 }, quick: { minHeight: 58, borderRadius: 6, borderWidth: 1, paddingHorizontal: 14, flexDirection: "row", alignItems: "center", gap: 12 }, quickText: { flex: 1, fontSize: 14, fontWeight: "700" }, tipCard: { flexDirection: "row", padding: 14, borderRadius: 6, borderWidth: 1, gap: 12 }, tipIcon: { width: 38, height: 38, borderRadius: 5, alignItems: "center", justifyContent: "center" }, tipTitle: { fontWeight: "800", fontSize: 14 }, tipText: { fontSize: 12, lineHeight: 17, marginTop: 4 } });
