import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { useWorkoutStore } from "@/lib/workout-store";
import { getExercise } from "@/lib/workout-data";

export default function ProgramsScreen() { const colors = useColors(); const { programs, startWorkout } = useWorkoutStore(); return <ScreenContainer className="px-5" containerClassName="bg-background"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><View style={styles.header}><View><Text style={[styles.eyebrow, { color: colors.primary }]}>ТВОИ ПЛАНЫ</Text><Text style={[styles.title, { color: colors.foreground }]}>Программы</Text></View><Pressable style={[styles.add, { backgroundColor: colors.primary }]} onPress={() => router.push("/program/new")}><Text style={styles.plus}>＋</Text></Pressable></View><Text style={[styles.subtitle, { color: colors.muted }]}>Собирай тренировки под цель и повторяй их с прогрессом.</Text>{programs.map((program) => <View key={program.id} style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.cardHeader}><View style={[styles.programIcon, { backgroundColor: colors.primary + "22" }]}><IconSymbol name="list.bullet" size={22} color={colors.primary} /></View><View style={{ flex: 1 }}><Text style={[styles.cardTitle, { color: colors.foreground }]}>{program.name}</Text><Text style={[styles.cardSub, { color: colors.muted }]}>{program.description}</Text></View><Pressable onPress={() => router.push({ pathname: "/calendar", params: { programId: program.id } })}><IconSymbol name="calendar" size={20} color={colors.muted} /></Pressable></View><View style={[styles.divider, { backgroundColor: colors.border }]} /><Text style={[styles.exerciseLine, { color: colors.muted }]}>{program.exercises.map((item) => getExercise(item.exerciseId)?.name).join("  ·  ")}</Text><View style={styles.cardFooter}><Text style={[styles.meta, { color: colors.muted }]}>{program.exercises.length} упражнения  ·  {program.exercises.reduce((sum, item) => sum + item.sets, 0)} подходов</Text><Pressable onPress={() => { startWorkout(program.id); router.push({ pathname: "/workout", params: { programId: program.id } }); }} style={[styles.start, { backgroundColor: colors.primary }]}><Text style={styles.startText}>Начать</Text></Pressable></View></View>)}<Pressable onPress={() => router.push("/program/new")} style={[styles.newCard, { borderColor: colors.border }]}><Text style={[styles.newTitle, { color: colors.foreground }]}>＋  Создать новую программу</Text><Text style={[styles.newSub, { color: colors.muted }]}>Настрой упражнения, вес, повторы и отдых</Text></Pressable></ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ content: { paddingTop: 18, paddingBottom: 32, gap: 14 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, eyebrow: { fontSize: 11, fontWeight: "800", letterSpacing: 1.2 }, title: { fontSize: 30, fontWeight: "800", marginTop: 5 }, subtitle: { fontSize: 14, lineHeight: 20, marginBottom: 4 }, add: { width: 43, height: 43, borderRadius: 14, alignItems: "center", justifyContent: "center" }, plus: { fontSize: 25, color: "#101412", lineHeight: 28 }, card: { borderRadius: 20, borderWidth: 1, padding: 15 }, cardHeader: { flexDirection: "row", alignItems: "center", gap: 11 }, programIcon: { width: 42, height: 42, borderRadius: 14, alignItems: "center", justifyContent: "center" }, cardTitle: { fontSize: 16, fontWeight: "800" }, cardSub: { fontSize: 12, marginTop: 4 }, divider: { height: 1, marginVertical: 13 }, exerciseLine: { fontSize: 12, lineHeight: 18 }, cardFooter: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 15 }, meta: { fontSize: 11 }, start: { borderRadius: 11, paddingHorizontal: 14, paddingVertical: 9 }, startText: { fontSize: 12, color: "#101412", fontWeight: "800" }, newCard: { borderRadius: 18, borderWidth: 1, borderStyle: "dashed", padding: 18 }, newTitle: { fontSize: 15, fontWeight: "800" }, newSub: { fontSize: 12, marginTop: 6 } });
